version: '3.8'
services:
  soc_target:
    build: .
    container_name: cybersim_soc_target
    hostname: SOC-ANALYST
    networks:
      cybersim_net:
        ipv4_address: 172.20.0.12
    environment:
      - CYBERSIM_FLAG=${CYBERSIM_FLAG:-FLAG{soc_default}}
    restart: unless-stopped

networks:
  cybersim_net:
    external: true
    name: networking_lab_cybersim_net
