[global]
workgroup = CORP
server string = CyberSim AD Server
security = user
map to guest = Bad User
log file = /var/log/samba/log.%m
max log size = 50
dns proxy = no

[shared]
path = /srv/samba/shared
browseable = yes
read only = no
guest ok = yes
comment = Public Shared Drive

[admin_only]
path = /srv/samba/admin_only
browseable = yes
read only = yes
valid users = admin it_admin
comment = Admin Only - Restricted

[it_dept]
path = /srv/samba/it_dept
browseable = yes
read only = yes
valid users = @it_department admin
comment = IT Department Files
